### PR TITLE
Ractive.js TypeScript DefinitelyTyped

### PR DESCRIPTION
**Pull request by dandeven**
This is the TypeScript definition for the Ractive.js 0.7.3.

### CODE REVIEW

**Comment by evs-chris** [comment]
I still haven't gotten around to giving typescript the old college try. The last time I looked in any depth, all of the definitions were published to a centralized repo. Are they now published with individual modules instead/in addition?

**Comment by MartinKolarik** [comment]
Yes, I think they changed it and publishing within individual modules in preferred now.

@dandeven @seriouz do you know if simply including this file in the npm package is enough for it to for with typings, or if there is anything else we need to do? I'd check myself, but didn't have time yet.

**Comment by dandeven** [comment]
Hi @MartinKolarik @evs-chris 
There isn't any official centralized repository where we can put Typescript Definitions yet. 
It doesn't hurt if **Ractive.js** had its own **OFFICIAL** Typescript Definition. I think would be nice and avoid a lot of headaches for those developers who uses Typescript.
Maybe creating a new repository inside the Github Organization ("ractivejs") for the Definitions files would do the job.
I'm at your disposal if any help is needed.

**Comment by MartinKolarik** [comment]
@dandeven please create a new directory "typings" and move the definition file there. I'll merge this then.

**Comment by dandeven** [comment]
Done @MartinKolarik

**Comment by MartinKolarik** [comment]
👍 thank you.

**Comment by codler** [comment]
ehm, Im quite late..
@dandeven There have always been a central repo https://github.com/DefinitelyTyped/DefinitelyTyped and Ractive definition are there.


and sorry to say that this definition in this PR have bad practice, it doesn't follow ghost module. http://definitelytyped.org/guides/best-practices.html

I will replace with my definition file since it have more comments and are also up to date and follows the best practice of a definition file.

**Comment by MartinKolarik** [comment]
@codler I know about DefinitelyTyped but didn't realize Ractive definitions were there. Either way, I think it's better to have them directly in the npm package. You are welcome to merge/replace them 😄

**Comment by dandeven** [comment]
I'm so sorry guys...  I didn't realize there was a **Best Practice Guide** for Typescript Definitions. My fault! Thanks @codler

**Comment by seriouz** [comment]
I didn't know either 😥

**Pull request merged**
