### PR TITLE
Revert "Make in-browser tests a little easier to run"

### PR DESCRIPTION
**Pull request by Rich-Harris**
Reverts ractivejs/ractive#1624

Am having some difficulty running the tests since merging this PR - not sure what's going on. Investigating

### CODE REVIEW

**Comment by Rich-Harris** [comment]
@evs-chris What if system tests were separated from unit/integration tests, and the system tests always loaded the bundle (and did away with RequireJS entirely)? Can't seem to reintegrate #1624 without everything falling apart on OS X. (No idea why that's happening.) Feels like it would be a step in the right direction anyway.

**Comment by evs-chris** [comment]
Sounds good to me! Troubleshooting requirejs loading issues is a real bear.

Getting the bundle working again helped tremendously already.

**Comment by martypdx** [comment]
> What if system tests were separated from unit/integration tests

Will it be possible to have both running automatically? I wouldn't want to have to choose one or the the other and not have feedback from both during development...

**Comment by Rich-Harris** [comment]
Yeah, that's essential. What I'm thinking is this: we just bundle everything. So `window.Ractive` is defined before the tests load, and any additional dependencies (be they test samples or modules within the Ractive codebase) get bundled up with the test module. In fact there probably isn't any real need to split the tests up into system v unit tests if they're all using that mechanism.

**Comment by evs-chris** [comment]
Oddly enough, current master builds nicely and the test suite runs without issue in Windows. I was hoping that it would fail there too so I could troubleshoot, but I got nothing.

**Comment by Rich-Harris** [comment]
Okay, some progress. This PR does away with Grunt in favour of `npm run`:

```bash
npm run serve    # equivalent of `gobble`, except it uses local copy of gobble-cli
npm run build    # does the job that `grunt` used to do
```

The ES6 modules are no longer converted to AMD, and RequireJS is no longer used. Loading test pages is, accordingly, much quicker.

Node tests (which live in `test/__nodetests`) use Mocha. Browser tests still use PhantomJS for the time being, using a rather low-budget, albeit functional, custom runner. Hopefully it'll be a bit easier to move towards JSDOM now (and possibly Mocha, for consistency).

The tests can be run with `npm test`, though you don't want to do this - it assumes all the relevant files are in `tmp`. Instead, do `npm run build`, as it calls `npm test` as part of its sequence.

Only outstanding task I'm aware of is a way to run the Promises/A+ tests. Though there's probably a case for reorganising the test suite a bit, since it's grown a bit wild and woolly over the months.

Would appreciate a second pair of eyes on this before merging, to make sure I'm not relying on locally installed modules or whatever. @evs-chris if you get a chance to try this out on Windows/Linux, that'd be really helpful. Thanks

**Comment by evs-chris** [comment]
Phenomenal effort! I gave up about half way through when trying to migrate the test suite around in December and wept in a huddled mass, so cheers to you.

I'll have a little time later this evening to troubleshoot, but here's what I got initially, all after an `npm i`, for good measure:

### Linux `gobble`
```
╭─ chris@walt-jr: ~/development/js/ractive  ≋ tmp …  [INS]
╰─➤ gobble                                                                                                                                                 1 ↵ 11:00
gobble: server listening on port 4567
gobble: livereload server running
gobble: 02-_6to5 done in 9481ms
gobble: 03-esperantoBundle done in 1222ms
gobble: 01-moveTo done in 2ms
gobble: 16-merge done in 6ms
gobble: 04-moveTo done in 0ms
gobble: 05-merge done in 6ms
gobble: 06-unknown done in 1482ms
∙∙∙∙∙∙∙ 07-es6transpiler running...
gobble: 07-es6transpiler transformation failed

>>>
===
/home/chris/development/js/ractive/.gobble/06-unknown/1/init/config.js
---
49:     isClient = ( typeof document === 'object' );
50:
51:     hasConsole = ( typeof console !== 'undefined' && typeof console.warn === 'function' && typeof console.warn.apply === 'function' );
52:
53:     try {
===
Errors transpiling code: ["line 51: console is referenced before its declaration","line 51: console is referenced before its declaration","line 51: console is referenced before its declaration"]
Error: Errors transpiling code: ["line 51: console is referenced before its declaration","line 51: console is referenced before its declaration","line 51: console is referenced before its declaration"]
    at Object.es6transpiler (/home/chris/development/js/ractive/node_modules/gobble-es6-transpiler/index.js:15:9)
    at Object.fn (/home/chris/development/js/ractive/node_modules/gobble/lib/builtins/map.js:83:29)
    at queue._run (/home/chris/development/js/ractive/node_modules/gobble/lib/queue/Queue.js:24:9)
    at process._tickCallback (node.js:419:13)
<<<
```

### Linux `npm run build`

```
╭─ chris@walt-jr: ~/development/js/ractive  ≋ tmp …  [INS]
╰─➤ npmr build                                                                                                                                                 11:05

> ractive@0.6.1 build /home/chris/development/js/ractive
> ./scripts/build.sh

> linting...
src/utils/parseJSON.js: line 14, col 5, Expected '}' to match '{' from line 13 and instead saw '['.
src/utils/parseJSON.js: line 14, col 6, Missing semicolon.
src/utils/parseJSON.js: line 14, col 17, Missing semicolon.
src/utils/parseJSON.js: line 14, col 17, Expected an identifier and instead saw ']'.
src/utils/parseJSON.js: line 14, col 18, Missing semicolon.
src/utils/parseJSON.js: line 14, col 18, Expected '(end)' and instead saw ':'.
src/utils/parseJSON.js: line 1, col 8, 'Parser' is defined but never used.
src/utils/parseJSON.js: line 2, col 8, 'getStringLiteral' is defined but never used.
src/utils/parseJSON.js: line 3, col 8, 'getKey' is defined but never used.
src/utils/parseJSON.js: line 11, col 5, 'JsonParser' is defined but never used.
src/utils/parseJSON.js: line 11, col 27, 'specialsPattern' is defined but never used.
src/utils/parseJSON.js: line 11, col 44, 'numberPattern' is defined but never used.
src/utils/parseJSON.js: line 11, col 59, 'placeholderPattern' is defined but never used.
src/utils/parseJSON.js: line 11, col 79, 'placeholderAtStartPattern' is defined but never used.
src/utils/parseJSON.js: line 11, col 106, 'onlyWhitespace' is defined but never used.

15 errors

npm ERR! ractive@0.6.1 build: `./scripts/build.sh`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the ractive@0.6.1 build script.
npm ERR! This is most likely a problem with the ractive package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     ./scripts/build.sh
npm ERR! You can get their info via:
npm ERR!     npm owner ls ractive
npm ERR! There is likely additional logging output above.
npm ERR! System Linux 3.16.0-2-ARCH
npm ERR! command "/home/chris/opt/bin/node" "/home/chris/opt/bin/npm" "run-script" "build"
npm ERR! cwd /home/chris/development/js/ractive
npm ERR! node -v v0.10.33
npm ERR! npm -v 1.4.28
npm ERR! code ELIFECYCLE
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /home/chris/development/js/ractive/npm-debug.log
npm ERR! not ok code 0
```

### Windows `gobble`
```
PS C:\dev\js\ractive> gobble
gobble: server listening on port 4567
gobble: livereload server running
gobble: build invalidated (4 files added). restarting
gobble: 02-_6to5 done in 235ms
∙∙∙∙∙∙∙ 03-esperantoBundle running...
gobble: 03-esperantoBundle transformation failed

>>>
Could not find entry module (Ractive)
Error: Could not find entry module (Ractive)
    at C:\dev\js\ractive\node_modules\gobble-esperanto-bundle\node_modules\esperanto\esperanto.js:1427:13
    at invokeCallback (C:\dev\js\ractive\node_modules\sander\node_modules\es6-promise\dist\commonjs\promise\promise.js:5
3:15)
    at publish (C:\dev\js\ractive\node_modules\sander\node_modules\es6-promise\dist\commonjs\promise\promise.js:98:5)
    at publishRejection (C:\dev\js\ractive\node_modules\sander\node_modules\es6-promise\dist\commonjs\promise\promise.js
:208:3)
    at flush (C:\dev\js\ractive\node_modules\sander\node_modules\es6-promise\dist\commonjs\promise\asap.js:35:5)
    at process._tickCallback (node.js:442:13)
<<<

gobble: build invalidated (14 files added). restarting
gobble: build invalidated (80 files added). restarting
gobble: build invalidated (8 files added). restarting
gobble: build invalidated (170 files added). restarting
gobble: build invalidated (6 files added). restarting
gobble: build invalidated (17 files added). restarting
gobble: build invalidated (124 files added). restarting
gobble: 02-_6to5 done in 357ms
gobble: build invalidated (232 files added). restarting
gobble: 02-_6to5 done in 177ms
∙∙∙∙∙∙∙ 03-esperantoBundle running...
gobble: 03-esperantoBundle transformation failed

>>>
Could not find entry module (Ractive)
Error: Could not find entry module (Ractive)
    at C:\dev\js\ractive\node_modules\gobble-esperanto-bundle\node_modules\esperanto\esperanto.js:1427:13
    at invokeCallback (C:\dev\js\ractive\node_modules\sander\node_modules\es6-promise\dist\commonjs\promise\promise.js:5
3:15)
    at publish (C:\dev\js\ractive\node_modules\sander\node_modules\es6-promise\dist\commonjs\promise\promise.js:98:5)
    at publishRejection (C:\dev\js\ractive\node_modules\sander\node_modules\es6-promise\dist\commonjs\promise\promise.js
:208:3)
    at flush (C:\dev\js\ractive\node_modules\sander\node_modules\es6-promise\dist\commonjs\promise\asap.js:35:5)
    at process._tickCallback (node.js:442:13)
<<<

gobble: build invalidated (122 files added). restarting
gobble: 02-_6to5 done in 12307ms
gobble: 03-esperantoBundle done in 372ms
gobble: 01-moveTo done in 37ms
gobble: 16-merge done in 53ms
gobble: 04-moveTo done in 215ms
gobble: 05-merge done in 1745ms
∙∙∙◦∙∙∙ 06-unknown running...
gobble: 06-unknown transformation failed

>>>
bundle.concat() can only be used with bundles that have no imports/exports
Error: bundle.concat() can only be used with bundles that have no imports/exports
    at concat (C:\dev\js\ractive\node_modules\esperanto\esperanto.js:2341:9)
    at Object.concat (C:\dev\js\ractive\node_modules\esperanto\esperanto.js:2398:40)
    at C:\dev\js\ractive\test\gobblefile.js:41:53
    at invokeCallback (C:\dev\js\ractive\node_modules\sander\node_modules\es6-promise\dist\commonjs\promise\promise.js:5
3:15)
    at publish (C:\dev\js\ractive\node_modules\sander\node_modules\es6-promise\dist\commonjs\promise\promise.js:98:5)
    at publishFulfillment (C:\dev\js\ractive\node_modules\sander\node_modules\es6-promise\dist\commonjs\promise\promise.
js:204:3)
    at flush (C:\dev\js\ractive\node_modules\sander\node_modules\es6-promise\dist\commonjs\promise\asap.js:35:5)
    at process._tickCallback (node.js:442:13)
<<<
```

### Windows `npm run build`
`npm run build` falls over in cmd or powershell, obviously, as they don't do shell.

**Comment by evs-chris** [comment]
I poked through working around the errors in the linux build and came back to post them, and behold, you already have commits that fix the issues. Dependency hell strikes again, it would seem. Linux is good now.

Windows gets a little further, though I'm not positive that the above errors weren't caused by Windows being Windows. Now it bails on a concat error:
```
PS C:\dev\js\ractive> gobble
gobble: server listening on port 4567
gobble: livereload server running
gobble: 02-6to5 done in 9637ms
gobble: 03-esperantoBundle done in 364ms
gobble: 01-moveTo done in 39ms
gobble: 16-merge done in 53ms
gobble: 04-moveTo done in 217ms
gobble: 05-merge done in 1816ms
∙∙∙∙◦∙∙ 06-unknown running...
gobble: 06-unknown transformation failed

>>>
bundle.concat() can only be used with bundles that have no imports/exports
Error: bundle.concat() can only be used with bundles that have no imports/exports
    at concat (C:\dev\js\ractive\node_modules\esperanto\esperanto.js:2341:9)
    at Object.concat (C:\dev\js\ractive\node_modules\esperanto\esperanto.js:2398:40)
    at C:\dev\js\ractive\test\gobblefile.js:41:53
    at $$$internal$$tryCatch (C:\dev\js\ractive\node_modules\sander\node_modules\es6-promise\dist\es6-promise.js:304:16)

    at $$$internal$$invokeCallback (C:\dev\js\ractive\node_modules\sander\node_modules\es6-promise\dist\es6-promise.js:3
16:17)
    at $$$internal$$publish (C:\dev\js\ractive\node_modules\sander\node_modules\es6-promise\dist\es6-promise.js:287:11)
    at $$asap$$flush (C:\dev\js\ractive\node_modules\sander\node_modules\es6-promise\dist\es6-promise.js:111:9)
    at process._tickCallback (node.js:442:13)
<<<
```

Tiny suggestion:
```diff
index be58712..6f53994 100644
--- a/test/gobblefile.js
+++ b/test/gobblefile.js
@@ -31,7 +31,7 @@ testModules = gobble([
        gobble( '__tests' ).moveTo( '__tests' ),
        gobble( 'testdeps' ),
        gobble( '../src' )
-]).transform( function ( inputdir, outputdir, options ) {
+]).transform( function bundleTests ( inputdir, outputdir, options ) {
        return sander.lsr( inputdir, '__tests' ).then( function ( testModules ) {
                var promises = testModules.map( function ( mod ) {
                        return esperanto.bundle({
```

**Comment by Rich-Harris** [comment]
Yep, was half-way through writing up those new commits but got sidetracked trying to get things to work in Windows....

Have updated a couple of the gobble plugins - gobble-es6-transpiler now lets you handle errors yourself, so the 'referenced before its declaration' nonsense gets squelched, and gobble-6to5 has been updated to use the just-released 6to5 2.10.0, which has some decent performance gains.

I've also included jshint as a devDependency, so the local copy should get used rather than a globally installed one. Hopefully that will fix the linting errors for good - it looks like the computed properties in the `parseJSON` module were throwing the linter off and causing it to report a load of errors that aren't there.

That `bundle.concat()` error is odd - it must be something to do with `/` versus `\` causing modules to not be found. WIIINNNDDDOOOOOWWWWWWSSSSS! (╯°□°）╯︵ ┻━┻

**Comment by evs-chris** [comment]
>  it must be something to do with / versus \ causing modules to not be found.

Yep. Once that is resolved, the build goes through and all the tests pass in-browser.

**Pull request merged**
