### PR TITLE
Tests & bug fixes

### PR DESCRIPTION
**Pull request by MartinKolarik**
Trying to get tests to pass in all browsers; current status:
 - [x] Chrome - all passing
 - [x] Opera - all passing
 - [x] Edge - all passing
 - [x] Firefox - ~~2 failing~~ - all passing
 - [x] IE 11 - ~~10 failing~~ - all passing
 - [x] IE 10 - ~~136 failing~~ - 106 failing / all passing in emulator or when run separately
 - [x] IE 9 - ~~138 failing~~ - 103 failing / all passing in emulator or when run separately

### CODE REVIEW

**Comment by MartinKolarik** [comment]
Looks like the IE emulator mode is just as shitty as the browser itself. Everything was passing in IE 10 & 9, then I fired up a real IE in VM... another 100+ tests failing there...

**Comment by evs-chris** [comment]
I say we take off and nuke it from orbit... it's the only way to be sure...

I am a bit surprised that emulation mode sucks that hard, but you're awesome for taking it that far :clap:. I dropped my last IE VM years ago.

With IE8 past end of life, and the rest of them following quickly, does anyone know when it's reasonable to rip out that chunk of legacy code and throw a party?

**Comment by MartinKolarik** [comment]
>With IE8 past end of life, and the rest of them following quickly, does anyone know when it's reasonable to rip out that chunk of legacy code and throw a party?

As far as I'm concerned, we could do that right now (at least for IE 8). But really, if we ever release v1.0.0, that would be a good time.

**Comment by fskreuz** [comment]
jQuery 3.0 will still do IE8 :smile: https://blog.jquery.com/2014/10/29/jquery-3-0-the-next-generations/comment-page-1/

**Comment by MartinKolarik** [comment]
>jQuery 3.0 will still do IE8

And Angular 2, Ember 2, and React 0.15 don't/won't :smile:

**Comment by MartinKolarik** [comment]
It seems most of the tests that were passing in an emulator but failing in real IE actually pass when run separately :grin:

Going to merge this, and maybe revisit another time...

**Comment by fskreuz** [comment]
I've seen this behavior a few times in other browsers as well. Could possibly be a QUnit issue, or the way we write the tests.

**Pull request merged**
