### PR TITLE
Special treatment for style and class attributes - RFC

### PR DESCRIPTION
**Pull request by evs-chris**
~~__Not ready yet... missing tests :smile:__~~

Transitions and decorators often need to twiddle classes or inline styles, but if the element also has class or style attributes, they are just blindly overwritten - #1262 #2404. This is my attempt to resolve those issues.

In both cases, the list of names/attributes set in the last run is kept around to see if anything that was set last time is no longer present and should be removed. There are a couple of tests failing now because the order of the constituents comes out a little different than just overwriting the attribute.

For the style side, the parser is just a char by char looped brute force reader. It has stood up to everything I've found to throw at it so far, though @MartinKolarik, as the wizard of textual state machines, could probably replace it all with a regex :smile:. Once the key/value pairs are pulled out of the string, they are iterated over and if the node's style object has a matching key, it is set to the value.

Thoughts?

### CODE REVIEW

**Comment by heavyk** [comment]
there may be a faster way to lookup if the class exists, but this is the right way to go.

maybe if classList were used (polyfilled if unavailable), all decorators and transitions could use that and not step on each other's toes.

https://developer.mozilla.org/en-US/docs/Web/API/Element/classList

**Comment by MartinKolarik** [comment]
>though @MartinKolarik, as the wizard of textual state machines, could probably replace it all with a regex :smile:.

Couldn't resist :smile: 
```js
// import camelCase from 'utils/camelCase';

const specials = { 'float': 'cssFloat' };
const remove = /\/\*(?:[\s\S]*?)\*\//g;
const escape = /url\(\s*(['"])(?:\\[\s\S]|(?!\1).)*\1\s*\)|url\((?:\\[\s\S]|[^)])*\)|(['"])(?:\\[\s\S]|(?!\1).)*\2/gi;
const value = /\0(\d+)/g;

function readStyle ( css ) {
	let rules = {};
	let values = [];

	css.replace( escape, match => `\0${values.push( match ) - 1}`)
		.replace( remove, '' )
		.split( ';' )
		.filter( rule => !!rule.trim() )
		.map( rule => rule.replace( value, ( match, n ) => values[ n ] ) )
		.forEach(rule => {
			let i = rule.indexOf(':');
			let name = camelCase( rule.substr( 0, i ).trim() );
			rules[ specials[ name ] || name ] = rule.substr( i + 1 ).trim();
		});


	return rules;
}
```

It should handle any valid CSS and is a little faster, so feel free to use it. Also, here's a valid CSS  that's failing with your parser: `background: url(/*xx);` (because URLs don't have to be inside quotes).

**Comment by fskreuz** [comment]
> ```js
.forEach(rule => {
  let i = rule.indexOf(':');
  let name = camelCase( rule.substr( 0, i ).trim() );
  rules[ specials[ name ] || name ] = rule.substr( i + 1 ).trim();
});
```

One less outer variable :smile: 

```js
.reduce((rules, rule) => {
  let i = rule.indexOf(':');
  let name = camelCase( rule.substr( 0, i ).trim() );
  rules[ specials[ name ] || name ] = rule.substr( i + 1 ).trim();
  return rules;
}, {});
```

**Comment by MartinKolarik** [comment]
@fskreuz :+1: updated my comment.

**Comment by heavyk** [comment]
yeah but your version is quite a bit more difficult to read. I prefer chris' implementation ... it just needs to be updated for `url()`

**Comment by evs-chris** [comment]
@MartinKolarik :+1:

I switched the parser because even though it's a bit harder to follow, it's considerably shorter and there's apparently a speed advantage. Plus if I cross my eyes just right it's easy to read :laughing:.

There are also a few tests and everything passes now that I've worked around weirdness in how phantom handles inline styles set from the DOM side.

**Comment by evs-chris** [comment]
In an odd turn of events, appveyor is succeeding where travis is not. It looks combination of various node versions and phantom cause inline style attributes to be updated in different ways? At this point, I suppose the easy way out is to just remove all white space for the comparison...

**Comment by evs-chris** [comment]
Any objections?

**Comment by martypdx** [comment]
@evs-chris my only concern would be if the perf impact for frequently updated values. Consider:

```html
<div style="transform: translate3d({{x}}px, {{y}}px, 1);">...</div>
```

Where `x` and `y` are set via a mousemove event. I know the number of styles/classes would be relatively small, but it is a `O(n^2)` process given use of `indexOf`.

Not directly related to this PR, I've wondered whether we should introduce attribute-based class and style syntax:

```html
<div class-foo="conditional" style-transform="translate3d({{x}}px, {{y}}px, 1);">...</div>
```

as an augmentation for this PR to more succinctly write and apply individual styles or classes.

**Comment by evs-chris** [comment]
> my only concern would be if the perf impact for frequently updated values

Fair enough :smile:

> I've wondered whether we should introduce attribute-based class and style syntax

I like it! - and it looks like it probably offers a way to address to performance concern, so done!

**Comment by martypdx** [comment]
> so done!

@evs-chris you rock :grin:

**Pull request merged**
