### PR TITLE
Fixes #1736 - multiple inline partials broken

### LINKED ISSUE #1736: Multiple inline partials broken in edge?
See this fiddle: http://jsfiddle.net/fsdy5na7/

In egde, the second partial is written to the template, and ractive.partials['partial2'] is an empty array.
Latest works as expected.

Edit: Traced it to commit 624f190787d50a7cd036db0ad758304936fa86ff

### PR DESCRIPTION
**Pull request by aphitiel**

### CODE REVIEW

**Comment by martypdx** [comment]
Thanks @aphitiel!

Don't see a github auto-link, so for the record: fixes #1736

**Comment by aphitiel** [comment]
Sorry @martypdx, first PR ever. If there is anything else - I'm eager to know:)

**Comment by martypdx** [comment]
@aphitiel PR looks stellar. github linking thing was fail on my part - I didn't realise it picked up issue in title and commits.

**Comment by evs-chris** [comment]
LGTM :+1:

**Comment by Rich-Harris** [comment]
Nice, thanks @aphitiel, and congrats on your first PR. Was a total scoping fail on my part, nothing intentional there.

**Pull request merged**
