### PR TITLE
Re: Bug 1856 {{#with obj}} should not render if obj is falsey

### PR DESCRIPTION
**Pull request by ISNIT0**
My first Ractive pull request, there may well be a better way of doing this.

https://github.com/ractivejs/ractive/issues/1856

### CODE REVIEW

**Comment by ISNIT0** [comment]
Pretty sure the Travis Build failing was nothing to do with me.

**Comment by Madgvox** [comment]
Unfortunately, that change causes many tests to fail, so it would be unsafe to merge this PR. However, I think this is more indicative of the importance of one of our long-term goals of making the ractive codebase easier to read and modify to users outside of the project. Thank you very much for your contribution regardless!

PS: In the future, you can make sure your changes don't break anything by running `npm start` in the command line, then navigating to `localhost:4567/test` in your browser as outlined in [this section](https://github.com/ractivejs/ractive#developing-and-building) of the readme. That will run the entire suite of unit tests on the library to ensure that everything still works like it's supposed to.

**Comment by ISNIT0** [comment]
Gotcha, I'll check them all out :)

**Comment by martypdx** [comment]
@ISNIT0 Thanks for the PR. The right place to do this is in the [Section$setValue}(https://github.com/ractivejs/ractive/blob/dev/src/virtualdom/items/Section/prototype/setValue.js). Need to add tests to `render` tests, and change the breaking tests that assume old behavior.

All that being said, I already changed this in #1740, so this should be the behavior for `0.8`.

**Comment by ISNIT0** [comment]
@martypdx Thanks :) if there are any pull requests you reckon are 'beginner level' then please do send them my way. I am just starting to use Ractive at my work and really would like to get into the community and learn the platform!

**Pull request closed without merging**
