### PR TITLE
Partial-based alternative to proxies - incl async components - RFC

### LINKED ISSUE #3099: Question: Async/lazy/dynamic components/elements
I've been pondering a few different things primarily related to decorators, async loading of components, and other dynamic-ish template things. Everything relates to dynamic/lazy loading of components and also to dynamic lightweight component-like elements.

**WARNING**: What follows is a long and rambly. The TL;DR is that I think a new simple template item that is a sort of component/partial/decorator/parser transform hybrid would be tremendously useful, especially for implementing future constructs as external plugins e.g. dynamic components (`<Component component-name="{{.type}}" ... />`) and async components (`<Async async-src="some/path" ... />`).

## Async components
Loading a component that loads and caches another component to use as a pass-thru should definitely be possible. Something like `<Async async-src="some/path/or/something" mapping1="{{.foo}}" etc="you get the idea"><loading>Not loaded yet...</loading>Stuff outside of the loading tag there is going to be supplied to the actual component as content...</Async>`. I think all it would take to implement that would be to add a low-level API that allowed a component to cause its host VDOM node to unrender and render again - like maybe `this.component.reload()`.

The placeholder component would need to be supplied with a way to turn a name/path string into a Promise for a component constructor, which with webpack would just be fronting `System.imports(path')`. It could then check its internal registry upon `config` and if the component was already loaded, skip displaying the placeholder, update the component VDOM name and maybe template a little, and trigger a deferred reload. If not loaded, go ahead and set up the placeholder render, start the async load, and wait until the load finishes to trigger the reload. All-in-all not terrible, though there is some mild abuse that would need to take place at the template AST level, but for a low-level component I think that's not unreasonable.

## Dynamic element constructs/lightweight component-ish things
Pseudo-related to that - 0.9 introduced experimental parser transforms, which allow you to supply a hooks that process templates on their way out of the parser and transform them at the element/component level. This is a very convenient process for things like turning `<card><title>stuff</title>some stuff</card>` into `<div class="ractive-material-card"><div class="ractive-material-card-title">stuff</div><div class="ractive-material-card-body">some stuff</div></div>`. Using that and a context alias to `@local`, you can achieve something like a lightweight component with no performance overhead. Obviously, you don't get things like complete data isolation, full instance event support, and independent custom css on your "component", but there is a pretty large class of widget-y components that don't call for those sorts of things.

That card may not be the best of examples, but it's a tremendously powerful thing for making declarative ui easy and dry. A full component for a material card is a pretty severe bit of overkill, especially if you have more than a small handful of them to render. My last round of performance estimates came up with a limit of 1000 components on a page for a reasonable initial render on desktop-class machines - and that number would preferably stay less than 100 for mobile-ish things. Plain template is wicked fast, comparatively.

The trouble is that the parser hooks have to be in place at build time when dealing with something like the ractive bin, which all production code hopefully does at some point. Being able to run a transform taking `<card>...</card>` at bind-time and turning it into the appropriate bit of template would remove a significant barrier to convenient use of something like parser transforms.

## Tying it together
So looking at both of those, it occurs to me that there may be cause to introduce a new simple VDOM item that is a placeholder for a bit of template that can cause itself to reload. Something like a decorator for partials, where you can take advantage of the template constructs available to elements and components and get a handle to the place in the VDOM to trigger a re-render of the placeholder. That would remove the overhead of the wrapping component for the `Async` above, as it would become an inline transform that would also skip the requirement of deferred re-render of an already loaded async components. It would also cover dynamic components, as that would just be the `Async` transform without the asynchronous part.

The dynamic element side is also covered, as the transform gets to return whatever template it needs to after having processed itself and its parts.

### PR DESCRIPTION
**Pull request by evs-chris**
## Description:

This is an alternative version of #3106 that builds on top of partials rather than introducing a new vdom construct. I have dubbed the updated partial items __super partials__ or macro partials. There aren't too terribly many functional differences between this an the proxy PR, notably

* `proxy` is replaced with `macro` e.g. `Ractive.macro( ( handle, attrs ) => ..., { options } )`
* macro partials live alongside regular partials e.g. `new Ractive({ partials: { macro: Ractive.macro(...) } })`
* rather than modifying a common template member of the intermediate object, this makes template updates a bit more explicit by giving the handle a `setTemplate` method that can be called at any time

This also adds support for async components - components that are initially set as a promise for a component or a function that returns a promise for a component - by using an inline macro partial that resets when the component constructor becomes available. You can even specify a loading placeholder by passing a special inline partial e.g.

```html
<SomeComponentThatIsAsync>
  {{#partial async-loading}}Loading...{{/partial}}
</SomeComponentThatIsAsync>
```

It might make sense to have an `async-loaded` partial too, to allow cross-fade transitions when the component loads in.

Note that an external dynamic async plugin would still be easily available if you prefer the `<Async component="{{name}}" />`-style usage.

## Status

~~This isn't exactly complete, as there are still quite a few tests that need to be added, most notably regarding plain partial syntax that resolves to a macro partial. I think a few hooks would be nice to, like `render` and `unrender`. There's a `teardown`, but in hindsight, it should probably be moved to `unbind` rather than `unrender` on the host partial.~~ There are now tests, and I think the hooks are appropriately set up.

~~I will be pushing out a demo build to npm once I've covered a few more bases. I'll add some more description and examples once that's done. Until then, if you're intereseted, you can take a look at the included tests to kinda get an idea of what you can do with this.~~

See [this comment](https://github.com/ractivejs/ractive/pull/3111#issuecomment-338322590) for published info and a playground.

Fixes #3099

### CODE REVIEW

**Comment by ghost** [comment]
So this means reserved partial names, yes?

**Comment by evs-chris** [comment]
For those wondering about the reserved partial names, yes, this introduces three new special names that only apply if a component happens to be async:

1. `async-loading` - if supplied, is rendered while the promise remains unresolved.
2. `async-loaded` - if supplied, is used to render the actual component rather than just dumping it into the template directly. This is handy for setting up a transition in without having to have custom code on the component to handle it being async, and it requires -
3. `component` - if using `async-loaded` this is the template that would be dumped straight into the parent were you not using `async-loaded`.

Only the first two are supplied by the user e.g.

```html
<cmp>
  {{#partial async-loading}}loading...{{/partial}}
  {{#partial async-loaded}}<div burst-like-an-alien-in>{{>component}}</div>{{/partial}}
</cmp>
```

Notice that the `component` partial is automatically provided.

I chose those names because there's not a lot of wiggle room for mistaking what they do. I'm certainly open to suggestions on any naming if there are any other opinions 😄

**Comment by evs-chris** [comment]
Here's the full skinny on async components support in this PR:

1. You can set a component in a registry as a promise e.g. `components: { cmp: import('./cmp.ractive.html').then(m => m.default) }` in webpack and any instances of `<cmp />` that try to render before the promise resovles will get a placeholder. This is where the `async-loading` partial passed into the component body comes into play. If there is one, the placeholder will consist of that template.

2. When the promise resolves, the placeholder will set the component on the current ractive instance so that future renders are fully sync. It will also take the original template e.g. `<cmp some="{{mapping}}">content</cmp>` and dump it into the placeholder, replacing the `async-loading` template if applicable.

    1. This is where the `async-loaded` template comes into play. If supplied, the `async-loaded` template is dropped into the placeholder, replacing the `async-loading` template if applicable. The original component template is the supplied as `{{>component}}` for use within the `async-loaded` partial.

3. It's probably not very helpful to shove a promise directly into the components hash because promises kick off immediately. This is where ractive's function support in most registries comes in handy: you just register a function that spins up the promise and returns _that_. This way, the component load doesn't start until absolutely necessary. `components: { cmp () => import('./cmp.ractive.html') }`

4. As it stands, the promise for the component is not considered by the promise that is returned by the current operation, if any. This means that if the component is in something like `{{#if foo}}<cmp />{{/if}}`, then the promise returned by `r.toggle('foo')` won't include the load of the component or any associated transitions. I thought about tying that in, but it seemed YAGNI for the amount of extra code and general overhead that would require.

5. All of this is implemented in one fairly small chunk of code [right here](https://github.com/ractivejs/ractive/pull/3111/files#diff-494895f3c944efbaf982db27bc155876R110). It's a macro partial that's built in because it's slightly more coupled to the ractive guts than would be possible to implement as a plugin. This is mostly because it steps in when a component is found to make sure that component constructor is not a promise (or `then`able, as it were).

**Comment by evs-chris** [comment]
I have pushed out a demo build to npm as `@evs-chris/ractive@1.0.0-macro-002`. [Here's](https://ractive.js.org/playground/#N4IgFiBcoE5QdgVwDbIDQgM5QNrgC74AOmkA9GQMYAm8AdAFabUCmyAlgG4x3wv5l4RALZkAAi06YAtJTAx2mMjACGlfFxZiAjHQAM+6cLUwA9tL16ATMrUbOLRtgC6AXwz4oIADzUuAAnZqAF4AHRB8FRgAc35wgD5vMj9OeND4dO9MSgUifH98AE8iFjCIlgAPATB8YWRwwJDw-BZhImQVFoT0-39vACNEQlN4fxHZDkoAazKxOkx+AAoAcg18ZBZltH9lgGEwFXhY6gBCZYBKBP3D2IL2dZYkweH4NIz8b0oo6n9MIo3ZKZkKYYGV+mYAO4ZED+frseDUaRrDbxAASbGB2wAZmZhP4VP4vjBqHQkkTqG9Qh9yfEAJL+A4OfzwUx3B7+SCLMnfSnU75sjZlAAyKj+CVp23wYBY-g6f0J322jJlBORjyoPPSVK1HwhKnuADEQbT8LzesBgABiIhRDQqZD4zCFeCUaTAlR+I6uVyfHlC0we+HRR3OyiE0xtEYseD4Ohx7nE+IWsg2mB25DenVJPWG42mzJkbK5U0gDDYSAgSgjeXk-zBfwAJTsmjoxhypkWOsWDO2nXwMEw-nOdfi-mAOqpEPh1FMELoYDrDIA3BOpXR7exRf6vsgVgB9Pfki4r95UsDzJbLMTAnd0NVbfGEAd3+4bc4n7Vrhb4AAqrXanQsIsAAGq5Ur4ASUHKMi1ha8SVP2KjSH2CjPCwmDeryn5UhalrsFi-gHuSL4PJmp74NhHwpIS0GyN8SKviwSbAER3wkRs3pJCkWEUbxyb4WRlE4cA8RVjG0b4IJvHgckXA8cB76rjA-CIDAozjuRVKIEQ1CAYsKGYMOwAMhe+ArNepi3vevZPpg7EsO+-iuKurgfpJaA6hpn4oewaGkP4OCrIxyzOB55GUJg-mgeRvR0LBq69FSfiYABhSQLCN5TG5lE2tQnrROlBgAKytNl0m1FE0TwoVdAlcIZW9L0VbAjA6WWlYHUNY1-RqFM0RmIgCKAi1bVYmNXW9P0pgVNImAHDOEKFf4VhEBUy2rf4ej+DEPWLHo2z7ZtB10NoAAs5wHf42gbUVG1bTtKh7Qdz2bSdVgXZt-gAMwbdda3SCta0PU9R2gwY70TbCIKsDA0iqH4iD+YDXXOTF-gJf4cX0WqY4Y1SWIjPgs3sAAXiw6W6HVXVUsYMTwtIU3DMINVUxjqOftFVKo4pGTwFig3qOwIyygG1C7BGRBRjGixGTqyn4Kpox8BC-gAAq4ooQGmFMI64+R34-uwwgsKYQyLDLuteeV2uLE2gsOHQCHRtQixW5RLRtB0LTpcs9LKiLHosD8oqhvIIym5gyCFMsYGSecPOfu432WHoCdxye7MutW+QwIuU4IrOdC5-WyuNs2DiuzqkQxPwPuWtXsT4FsVf-l75M7PXreAc37y6ZE6Vu4QjE+7s-KGw8MfvO4Oqpum-mD+SOrT+8VaRnwMbz6uOb4EaMAmul7pixLUsUVP6SuO+ICuEAA) a little demo with a macro partial and an async component if you want to play around a bit. I added an `aliasLocal` method to the macro partial handle so that macros can have local data without mucking about in the context.

It also occurred to me that there should probably be an `async-failed` partial for async components in case the promise rejects for some reason, no?

**Comment by evs-chris** [comment]
There's now an `async-failed` special partial for async components, to be used should the component promise be rejected. The error is set on the macro-local model with an alias made available within the macro as `error`, so with a typical error, you can display a message with `{{error.message}}` if you need to.

I feel like this is pretty well done and is much better than the proxy version. The only thing that seems like it would be a near-necessity would be having the ability to block same-named partials from being loaded within the nested template by allowing a partial registry on the macro.

Any objections to using the partial registry for macro partials rather than some other registry? Either way, the partial vdom item will be responsible for them.

Any objections to going ahead and merging this as experimental to be made available in the next 0.9 release?

**Comment by ghost** [comment]
LGTM 👍

**Comment by ceremcem** [comment]
When something fails, we might want to show something via `async-failed`, but we would probably retry or do something else via a handler (function).

**Comment by evs-chris** [comment]
That's a bit beyond the scope of what ractive can handle. You'd need to cover that in the promise that you hand to ractive e.g.

```js
MyComponent: () => import('MyComponent.html').then(module => module.default, error => {
  // here's your opportunity to do advanced error handling/retry
});
```

**Pull request merged**
