### PR TITLE
Adaptor teardown fixes

### LINKED ISSUE #3112: Is ractive.get supposed to return the original form of the data?
## Description:

Instead of a long description, a picture paints a thousand words.

capture

The adaptor specifically tells Ractive to preserve the model when reset with a POJO on the adapted keypath. Therefore, a `ractive.get()` after a `ractive.set` with a POJO on the adapted keypath should return the Backbone model.

Expected:

- `ractive.get()` returns the model (`model1`)
- `ractive.get()` with `unwrap: false` returns the POJO representation (`model2`). 
- Adaptor would still work, updating in both directions.

Actual:

- Both `ractive.get()` return the POJO after a `ractive.set()` (`model3` and `model4`)
- Adaptor still works on the same model.

Digging in, it seems that after the `ractive.set()`, the `value` (holds the POJO version) and `wrapperValue` (holds the original data) are now both holding the POJO value.
## Versions affected:

0.7.3 and newer

## Reproduction:

```html
<script src="https://cdn.jsdelivr.net/npm/underscore@1/underscore.js"></script>
<script src="https://cdn.jsdelivr.net/npm/backbone@1/backbone.js"></script>
<script src="https://cdn.jsdelivr.net/npm/ractive@0.9.5/ractive.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/ractive-adaptors-backbone@0.3.0/dist/ractive-adaptors-backbone.min.js"></script>
```

```js
const model = new Backbone.Model({ message: 'hello' })
const instance = Ractive({ adapt: [ 'Backbone' ], data: { model } })

debugger;
const model1 = instance.get('model')
const model2 = instance.get('model', { unwrap: false })
debugger;
instance.set('model', { message: 'world' })
debugger;
const model3 = instance.get('model')
const model4 = instance.get('model', { unwrap: false })
debugger;

t.strictEqual(instance.get('model'), model)
t.strictEqual(instance.get('model.message'), model.get('message'))
```

### PR DESCRIPTION
**Pull request by ghost**
## Description:

Fixes a bunch of adaptor teardown bugs coming from work on the backbone and promise adaptors in https://github.com/ractivejs/ractive/pull/3052

## Fixes the following issues:

#3112 
#3100

## Is breaking:

Nope, or at least according to the tests

### CODE REVIEW

**Review by evs-chris — APPROVED** [review]
LGTM! The tests are 👌, and this has to be the most tested 4 line change ever 😁

**Comment by ghost** [comment]
Consider this preparation for the adaptor overhaul 😄 And its going to be fun when I bring in the rxjs, ampersand, and bacon adaptors.

**Comment by ghost** [comment]
Effects of writing code in poorly-lit conditions 😂

**Comment by ghost** [comment]
Feel free to merge and release at the next possible opportunity. 😁

**Pull request merged**
