### PR TITLE
Fix event expression Function scope when called

### PR DESCRIPTION
**Pull request by JonDum**
A la https://github.com/ractivejs/ractive/issues/2019

Just adds a simple check to see if the item is a function and if so, binds it to the instance.

### CODE REVIEW

**Comment by fskreuz** [comment]
Not to be nitpicky but... `===`?

**Comment by JonDum** [comment]
@fskreuz not needed with typeof. Always returns a string and when comparing with another string no conversion will occur

**Comment by fskreuz** [comment]
Nearby code a few lines down uses `===` for `typeof` so... uniformity :D

**Comment by martypdx** [comment]
Thanks for the PR @JonDum!

IMO `==` means "something special happening here" (like `foo == null` ), so agree with @fskreuz that if vanilla string compare, use `===`.  

Also, need to add a test in [events](https://github.com/ractivejs/ractive/blob/dev/test/__tests/events.js)

**Comment by fskreuz** [comment]
IIRC, one should use tabs instead of spaces for indents. More on https://github.com/ractivejs/ractive/blob/master/CONTRIBUTING.md

**Comment by JonDum** [comment]
Something must have been screwed up with .editorConfig in my vim. It looked right in Vim, but not in GH I guess. Should be tab characters now.

**Comment by Rich-Harris** [comment]
@JonDum Thanks for this PR. Tabs vs spaces aside (and [GitHub really should get their act together on that...](https://github.com/isaacs/github/issues/170) probably my most commented issue ever), this fix will unfortunately be swept aside by #2022, so it's probably best we *don't* merge it, so that it stays open and we don't forget about it.

>  I'm not sure where/how to put a test case for this though.

The same applies to any tests as to the PR itself. [This'll do for now](http://jsfiddle.net/36e3wycs/) - we'll just have to ensure that it goes into the test suite before #2022 is merged. I'm tied up with a gazillion other things at the moment but if anyone wants to submit an equivalent PR against the arboretum branch it would be gladly received!

**Comment by Rich-Harris** [comment]
We stumbled upon a better way of approaching this problem – binding functions on init/set (#2115) – so I'll close this PR. The test from the fiddle above is included via #2111

**Pull request closed without merging**
