### PR TITLE
Fixes computations referencing mappings that throw when the mapping resolves

### LINKED ISSUE #1645: "d.dep.setValue is not a function" on nested components
I'm trying to use edge version and found some bug. I've prepared testcase as usual)

Bug appears after merge #1546 and looks related to #1542.

My case: http://jsfiddle.net/d4sgqma2/

All items are required to reproduce - `component1` inherits values from root object, `component2` rewrites context and uses function call and value is defined after first initialization.

Function itself isn't important — it fails with any one. http://jsfiddle.net/d4sgqma2/1/

```js
new Ractive({
    el: 'body',
    template: '<component1 />',

    components: {
        component1: Ractive.extend({
            template: '<component2 foo="{{ bar }}" />',
        }),

        component2: Ractive.extend({
            template: '{{ console.log(foo) }}',
        }),
    },
    
    onrender: function() {
        this.set('bar', 1);
    },
});
```

### PR DESCRIPTION
**Pull request by evs-chris**
This fixes #1645. I'm not 100% positive that this is the correct resolution for this, but it does work. Is there a better place to handle this and/or is there another corner case to cover?

Hat tip to @anton-ryzhov again for an excellent test case!

### CODE REVIEW

**Comment by anton-ryzhov** [comment]
Great! So fast!
I'd been localizing bug for a longer time)

**Comment by martypdx** [comment]
I remember this use case back when we started on Bindings. Would be nice to standardize viewmodel dependent API so logic didn't need to be special cased, but what you have LGTM.

**Comment by evs-chris** [comment]
Something like `viewmodel.resetValue( dep, value )` that would basically call `setValue` for `'default'` deps and trigger recomputation for `'computed'` deps without the full `mark` running?

**Comment by martypdx** [comment]
Yeah, though ideally it's something on the dependent, so maybe computations have an implementation of `setValue` (and maybe it gets renamed `resetValue`). Goal is that code that iterates deps shouldn't have to know what "kind" of dependent it is:

```js
this.deps.forEach( d => {
    d.dep.doSomething();
});
```

**Pull request merged**
