### PR TITLE
Update AppVeyor config

### PR DESCRIPTION
**Pull request by MartinKolarik**
**Description of the pull request:**
Removes node `0.10` and `1.0` from AppVeyor.

### CODE REVIEW

**Comment by fskreuz** [comment]
Is there a reason to use older versions of Node? Can we just go with 4 and 5?

**Comment by MartinKolarik** [comment]
We could, but as long as we want to support 0.10 / 0.12, we should probably run tests on that. I tried adding 4 and 5 as well, but each build on AppVeyor takes forever to complete, so I decided to go with just 0.12.

**Comment by Rich-Harris** [comment]
Ideal situation would be to build it using Node 5 but then test it using different versions we want to support. Is there a straightforward way to do that? Any reason it wouldn't be possible to use nvm inside Appveyor?

**Comment by MartinKolarik** [comment]
@Rich-Harris if we want to run tests on multiple node versions, I'd do that on Travis. It supports concurrent builds and is much more reliable. We only need to change the setup so that only one node version runs the deployment script.

**Comment by MartinKolarik** [comment]
Yay, four green lights!

**Comment by Rich-Harris** [comment]
> Yay, four green lights!

:cocktail: 

> if we want to run tests on multiple node versions, I'd do that on Travis

That makes sense to me – should we update this config so that it always uses stable node, if it's only to ensure that developers can build the library on Windows? If we did that, and required node>=5 to build the lib, we might even be able to avoid transpiling the test .js files with Babel, which would be nice

**Comment by MartinKolarik** [comment]
>should we update this config so that it always uses stable node, if it's only to ensure that developers can build the library on Windows

Makes sense, I changed it to v5, and am going to setup Travis.

>If we did that, and required node>=5 to build the lib, we might even be able to avoid transpiling the test .js files with Babel, which would be nice

:+1: I think that's a perfectly fine requirement

**Comment by Rich-Harris** [comment]
> we might even be able to avoid transpiling the test .js files with Babel

actually, that's nonsense... we still need to support older browsers! D'oh

**Comment by fskreuz** [comment]
> actually, that's nonsense

The node tests can use ES6 to some degree if run in the latest Node. The browser tests would still need transpilation though.

**Comment by MartinKolarik** [comment]
>actually, that's nonsense... we still need to support older browsers! D'oh

lol, you are right :laughing:

**Pull request merged**
