### PR TITLE
using removeChild(firstChild) instead of innerHTML = ""

### PR DESCRIPTION
**Pull request by brakmic**
According to several tests innerHTML is not only slower than removeChild but also less performant than innerText: https://developer.mozilla.org/en-US/docs/Web/API/Node/textContent

I don't know how helpful my pull request is but the tests seem to be unambiguous.

http://jsperf.com/innerhtml-vs-removechild/15
https://jsperf.com/innerhtml-vs-removechild/96

Maybe there's a better explanation on how to properly use innerHTML/removeChild?

I hope the sources are properly formatted now. I had to revert the patch because of Tabs requirements from guidelines. Sorry.

### CODE REVIEW

**Comment by fskreuz** [comment]
This looks good to me, but I'm unsure. Waiting for more eyes to take a look.

**Comment by MartinKolarik** [comment]
`textContent` is not supported by IE 8. I personally couldn't care less, but since we still maintain the legacy version, this is a problem.

**Comment by MartinKolarik** [comment]
Not the mention both linked benchmarks are completely broken. [Here's one that should be correct](http://jsperf.com/innerhtml-vs-removechild/376), and it's in line with my previous testing.

**Comment by brakmic** [comment]
Wow, thanks! Learned something new. I must admit I can't recognize why the other tests are broken but after some time I'll uncover the secret.

Many thanks.

I think I should close this request, ok?

**Comment by MartinKolarik** [comment]
>I must admit I can't recognize why the other tests are broken but after some time I'll uncover the secret.

Because `Benchmark.prototype.setup()` which is used to populate the element is called once before each test, not before every iteration, so once the children are removed, the element remains empty during the whole test.

**Comment by brakmic** [comment]
Oops, now I understand it. :smile: Thanks for the clarification.
I'll now close this superfluous pull request. 

Regards,

**Pull request closed without merging**
