### PR TITLE
Fix infinite hardlink on linux

### PR DESCRIPTION
**Pull request by ghost**
## Description of the pull request:

The hardlink gobble transform is causing infinite watch cycle on linux. This reverts it back to the copy version.

## Fixes the following issues:

https://github.com/ractivejs/ractive/pull/2943#issuecomment-303273645

## Is breaking:

Nope

## Reviewers:

@evs-chris

### CODE REVIEW

**Comment by evs-chris** [comment]
With this, I'm not getting the loop, but I also am not seeing the tests, which is really weird, cause they're clearly included. I think I'm missing something...

**Comment by evs-chris** [comment]
Ah! Moved to `qunit`?

**Comment by ghost** [comment]
Yep. Moved it so that sourcemap `tests` doesn't merge with the served `tests`.

**Comment by evs-chris** [comment]
Gotcha. LGTM 😄

**Pull request merged**
