### PR TITLE
See if appveyor will succeed on the second run too

### PR DESCRIPTION
**Pull request by evs-chris**
Just curious...

### CODE REVIEW

**Comment by Rich-Harris** [comment]
looks like gobble is having a panic attack. Wonder if it's because a load of temporary files are being created or something, and if so why that doesn't seem to be the case when running in a VM locally.

**Comment by evs-chris** [comment]
I think when the queue eventually flushes, that last build script change will work for appveyor. I don't think it's really gobble's fault... more like something whacky about the windows filesystem. I've *only* managed to reproduce what happens on appveyor once on my machine, just after a clean checkout and fresh `npm install`. Subsequent attempts were met with horrible success.

**Comment by Rich-Harris** [comment]
Seeing the reports roll in from Appveyor and Travis has been like watching the world's nerdiest comedy. [Yakety Sax](https://www.youtube.com/watch?v=MK6TXMsvgQg) is playing in my head

**Comment by evs-chris** [comment]
Yeah... I think I've been chased through every entry in the corridor now...

**Comment by martypdx** [comment]
> Yakety Sax is playing in my head

Is Travis the white llama? or the black?

**Comment by Rich-Harris** [comment]
:laughing: the white llama was the quicker of the two, so Appveyor is definitely black

**Comment by evs-chris** [comment]
Hah! The llamas have been captured!

I hadn't seen that one yet, so thanks for that.

**Pull request merged**
