### PR TITLE
0.7

### PR DESCRIPTION
**Pull request by Rich-Harris**
**NOT READY FOR MERGE!**

I thought it would be worth creating a pull request for 0.7 so that we can have some visibility about remaining tasks. If you think of other stuff, mention it - we can add it to this comment so it stays organised

* [x] Triage issues - there's a [milestone](https://github.com/ractivejs/ractive/issues?q=is%3Aopen+is%3Aissue+milestone%3A0.7.0) for 0.7.0, but a lot of open issues that should be on it aren't
* [x] Close all issues on said milestone
* [x] Changelog
* [ ] Bring documentation up-to-date

    *@evs-chris has taken care of this, just a matter of renaming edge -> 0.7 when we release*
* [ ] Migration guide

    *ditto*
* [x] Cross-browser testing - yes, even IE8

Other stuff that will need to happen:

* [x] The [template spec](https://github.com/ractivejs/template-spec) needs to be updated, we're now on v3.
* [ ] [rcu](https://github.com/ractivejs/rcu) (the component loader utility) and its various dependents (rvc, rv, ractify, gobble-ractive, broccoli-ractive, ractive-component-loader) need to be updated and released at the same time. Many of these also have [edge branches](https://github.com/ractivejs/rcu/tree/edge)

    *pull requests for these: https://github.com/ractivejs/rcu/pull/12, https://github.com/ractivejs/rcu-builders/pull/1, https://github.com/ractivejs/rvc/pull/10, https://github.com/gobblejs/gobble-ractive/pull/1*

* [ ] Blog post and announcement etc

## Stuff we can do post-release, but preferably sooner rather than later

* [ ] Non-self-registering plugins (see [this mailing list discussion](https://groups.google.com/forum/#!topic/ractive-js/HwDxpGak3ic)) - should update as many as possible. Some plugins already have an `edge` branch that's ready for that switch (e.g. [ractive-events-tap](https://github.com/ractivejs/ractive-events-tap/tree/edge))
* [ ] Similarly, the plugin template will need to be brought up-to-date
* [ ] Changes to the adaptor plugin API (which may be necessitated by #1775) would need to be clearly signposted, and reflected in existing plugins
* [ ] Examples and tutorials must be updated

### CODE REVIEW

**Comment by martypdx** [comment]
thanks for pulling this together @Rich-Harris

**Comment by evs-chris** [comment]
I've been trying to keep the edge docs up to date as we go. I think I have all of the major things covered up through mid-February, so there shouldn't be too much to do there beyond rename add 0.7 to the template, rename edge to 0.7, and copy 0.7 to edge. I'd be happy to try to take care of that and the template spec along with whatever issues I can. Do you have a timetable in mind?

**Comment by Rich-Harris** [comment]
@evs-chris you legend!

> Do you have a timetable in mind?

Not as such, just keen for us to ship as soon as possible - I have a relatively clear work schedule at the moment but there's never any telling how long that'll last, so I'm trying to make hay while the sun shines

**Comment by Rich-Harris** [comment]
I think we're... ready? As long as no-one can think of any particular reasons not to, I reckon we can merge #1845 and release (followed quickly by ractivejs/rcu#12, ractivejs/rcu-builders#1, ractivejs/rvc#10, gobblejs/gobble-ractive#1, and a switchover on the docs site).

Once that's done I'll cobble together an announcement of some form, then we can tie up the loose ends (plugins, basically), then onwards to 0.8.

Sound good?

**Comment by evs-chris** [comment]
Sounds good to me. I've been tracking edge fairly closely for the last few days and haven't seen anything pop up beyond what's already been taken care of. So :+1:

**Comment by martypdx** [comment]
I noticed one thing, and it might just be my misunderstanding, but if you push to an array, all of the indexes get marked as `newIndices`

**Comment by martypdx** [comment]
Here, [line](https://github.com/ractivejs/ractive/blob/dev/src/shared/getNewIndices.js#L41) shouldn't that be: `for ( i = 0; i >= removeStart; i += 1 )`?

**Comment by Rich-Harris** [comment]
Have just checked and I think it's behaving correctly - if I push to an array with three items, `newIndices` is `[0,1,2]` (i.e. nothing has changed). Are you seeing something different?

**Comment by martypdx** [comment]
Just had a chance to run through it with the debugger and it's the `touchedFrom` that matters. It was something I had noticed the other day, and hadn't had a chance to fully go check it out.

So looks good :+1:

**Comment by martypdx** [comment]
Improvements across the board vs `0.6.1` :sunglasses: 

image

image

image

image

image

**Comment by Madgvox** [comment]
Awesome!

**Comment by Rich-Harris** [comment]
vwmin

**Comment by evs-chris** [comment]
Just wanted to note that I'm doing some tweaks to the docs for last-minute changes. Anyone have anything in particular they'd like adjusted?

**Comment by Rich-Harris** [comment]
Was just about to mention - I went ahead and copied the edge docs to 0.7. I can't think of anything off the top of my head

**Comment by Rich-Harris** [comment]
Thanks for keeping them up to date by the way! I know how tedious that stuff is

**Pull request merged**
