### PR TITLE
Implementation of link/unlink for mapping keypaths within a viewmodel - RFC

### PR DESCRIPTION
**Pull request by evs-chris**
This ~~takes advantage of the work done on mappings~~ to alias one keypath to another root (symlink) within a single viewmodel. This is particularly handy for master/detail-type scenarios where you want to do something like:
```html
<ul>{{#each items}}<li on-click="link(@keypath, 'selected')">{{ .name }}</li>{{/each}}</ul>
<label>Name: <input value="{{ selected.name }}" /></label><br/>
<label>Priority: <input type="number" value="{{ selected.priority }}" /></label>
```

It's even more convenient when the data is hierarchical. With this changes to either the source or destination are reflected in both places as long as the link is in place. It introduces two additional methods on both the Ractive ~~and ViewModel~~ prototypes.

```js
Ractive.link( source /*: string */, dest /*: string */ ) /*: Promise */
Ractive.unlink( dest /*: string */ ) /*: Promise */
ViewModel.link( source /*: Keypath */, dest /*: Keypath */ )
ViewModel.unlink( dest /*: Keypath */ )
```

If the `dest` is already mapped, it will be remapped. If there is already a "real" value for `dest` it will be shadowed until it is unlinked.

### CODE REVIEW

**Comment by evs-chris** [comment]
I've been working around this for a while by manually `update`ing shared keypaths for a while, but someone other than me (#1720) ran into it and I figured I'd take a swipe at a cleaner solution.

**Comment by martypdx** [comment]
Freakishly clever @evs-chris :)

**Comment by martypdx** [comment]
Can you hose up component mappings if you're not careful?

**Comment by evs-chris** [comment]
I suppose you could... I didn't really consider that. But not anymore!

**Comment by evs-chris** [comment]
Also forgot to mention that, due to the way mappings work, link `dest`s can only be at the root. Once @martypdx gets the keypath deps and keypath aliases implemented :wink:, deeper keypaths could be allowed.

**Comment by martypdx** [comment]
Hey @evs-chris, I thought about this some more and I wonder if it would work better to register a dependency. Something like:

```js
function link( there, here ) {
    this.register( here, function( value ) {
        this.set( there, value );
    }.bind(this) );

   this.register( there, function( value ) {
        this.set( here, value );
    }.bind(this) );
}
```

But with some tracking for teardown, unlinking, etc.

That way it works with any keypaths, including across component boundaries.

**Comment by martypdx** [comment]
btw - one way I've found that gives you the two way binding is to use an index with a keypath expression (http://jsfiddle.net/ptjadb5d/):

```handlebars
    {{#items:i}}
      <li on-click='set("selected", i)'>{{name}}, {{job}}
    {{/}}
    {{#with items[selected] }}
      <input value="{{ name }}"/>
      <input value="{{ job }}"/>
    {{/with}}
```

**Comment by dagnelies** [comment]
This sounds like a useful feature. However, I wanted to dig a bit more about how it's meant to work.

Let's assume `link('foo','bar')`

Whenever `foo` or `bar` is updated, in an input field for example, both are updated, right? Or is it just "one-way" which would be kind of catastrophic.

Does it also work within/accross components?

> If the dest is already mapped, it will be remapped. If there is already a "real" value for dest it will be shadowed until it is unlinked.

IMHO, I think this would be an unexpected behavior. More expected would be to either null it or place a copy of the data.

**Comment by Rich-Harris** [comment]
This looks *awesome*. I'm under the cosh so can't look at the implementation right now, but in the meantime

**Comment by evs-chris** [comment]
I just added an implementation based on @martypdx's suggestion to just register dependencies. I modified `ViewModel.applyChanges` a little ( supply a keypath to `setValue` and allowing refining bindings to match based on a regex ) to make it easier. This version allows non-root links and does not shadow data, since it does a shallow copy when the link is set up. It also sets the link keypath to undefined on `unlink`. The mapped implementation is still in place for comparison.

@martypdx That's a handy method I've actually used before, but it falls over with hierarchical data. I had to fall back to manual updates and/or observers on the project I'm working on right now (trees).

@dagnelies It should work as expected when used with twoway bindings (see the tests). It should also work as expected across/within components since it basically just triggers `update`s when either side changes. The mapping version should work as well, as long as the link and component mappings don't overlap.

**Comment by evs-chris** [comment]
Superceded by #2172

**Pull request closed without merging**
