### PR TITLE
encourage use of data functions with Ractive.extend()

### PR DESCRIPTION
**Pull request by Rich-Harris**
The idea here is to ensure that people don't run into weird bugs in which an instance of a component accidentally mutates that component's default data, by suggesting the use of data functions instead of data objects.

I'm trying something slightly different here - printing example code to the console (ES6 template strings ftw!). Takes up a few lines, but is maybe more useful than trying to explain things, or send people to an explainer page on the docs.

screen shot 2015-03-13 at 4 13 03 pm

Any thoughts?

### CODE REVIEW

**Comment by martypdx** [comment]
Love including the examples.

SInce the console functions no longer consider debug state (I think), would this mean if someone wanted to do this their app would forever console warn?

**Comment by evs-chris** [comment]
:+1: I'm pretty sure I still do the wrong thing half of the time.

Would definitely prefer it didn't warn outside of debug (non-minified? :wink:) mode.

**Comment by Rich-Harris** [comment]
Yeah, this seems like another good reason for `Ractive.DEBUG` (#1793). Maybe we implement that, then replace `warn` and `warnOnce` with `alwaysWarn`, `alwaysWarnOnce`, `warnIfDebug`, `warnOnceIfDebug`? (and maybe `fatalIfDebug` if we find we need it)

How does that sound? Suggestions for better names welcome...

**Comment by evs-chris** [comment]
My $0.02:

To warn, no matter the mode: `warn`, `warnOnce`
To warn if only in DEBUG: `warnIfDebug`, `warnOnceIfDebug`
To warn or throw the error in DEBUG: `warnOrThrowIfDebug`

Having now repeated 'warn' a dozen or so times in my head, it seems a very strange word.

**Comment by martypdx** [comment]
I still think we should add the ractive instance to the console wrapper functions, i.e.:

```js
warn( ractive, 'this is why I'm warning you' );
```

Two reasons:

1) I think it would reduce the number of methods (maybe not) because the debug state is implicit,
2) We can add richer log output by identifying info about the ractive instance. Certainly easy things like `ractive.component ? ractive.component.name : 'root'`, but also the `ractive.el` or `ractive.find('*')` which will cause the component to light-up in the browser on hover so you can see exactly where the problem is (assuming it made it to render).

**Comment by Rich-Harris** [comment]
@evs-chris like it, will go with those. Though the more I think about it the more I wonder if there's a real use case for 'warn in prod, throw in dev' - part of me things that an error is an error and the only difference between dev and prod should be the verbosity of the feedback we give. Do you guys agree?

@martypdx yes, I think that's a really nice idea. Am currently poking around in this stuff, so I'll implement it and see what happens

**Comment by constantx** [comment]
:+1:

**Comment by martypdx** [comment]
> part of me things that an error is an error and the only difference between dev and prod should be the verbosity of the feedback we give. Do you guys agree?

Just go with it and try it out :)

**Pull request merged**
