### PR TITLE
remove old polyfills that should not be needed for IE9+ - #3038

### PR DESCRIPTION
**Pull request by paulie4**
for https://github.com/ractivejs/ractive/issues/3038

### CODE REVIEW

**Comment by evs-chris** [comment]
Looking at the [kangax ES5 table](http://kangax.github.io/compat-table/es5/) and checking [caniuse](http://caniuse.com), I'd say it's safe to remove all of these. After that, there're only two polyfills left out of the main build - `performance.now` and `requestAnimationFrame`, which aren't particularly big, so it'd probably make sense to just include them in the main build as well?

**Comment by ghost** [comment]
Yup. If we're only supporting IE11, pretty much all ES5 and web polyfills can be removed.

**Comment by evs-chris** [comment]
According to the kangax chart, we would still support IE9+. We might lose some very old versions of safari or the android browser, but it looks like even those are partially supported enough to get by.

**Comment by paulie4** [comment]
What features won't work for "some very old versions of safari or the android browser?" I see in kangax that a few JS engines fail on "Enumerable properties can be shadowed by non-enumerables" (which I think should be worded in reverse), and "Array.prototype.sort: compareFn must be function or undefined," both of which do seem like very edge case problems.

**Comment by ghost** [comment]
I think "android browser" means pre-"Chrome WebView" Androids, versions below 4.4 that don't use Chrome as internal browser. Apple keeps iOS fairly updated so this shouldn't be an issue, unless you still use an iPhone 5 (which I think Apple ditched recently because they're not 64-bit) or older (which don't get iOS updates anymore).

Not familiar with the API support for those browsers.

**Comment by paulie4** [comment]
@evs-chris, in [this comment](https://github.com/ractivejs/ractive/issues/3038#issuecomment-314262442) you mentioned the "polyfills [will be] in the default build", and in a comment in this PR, you said, "it'd probably make sense to just include them in the main build as well." What did you mean by "default build" versus "main build"? Also, are you thinking of putting the few remaining polyfills within built `ractive.js`, or would the build still have a separate `polyfills.js` file?

**Comment by evs-chris** [comment]
default build, main build, and ractive.js are all the same thing in my ramblings.

It didn't really make sense to have a polyfill for two tiny functions, so I pulled them into ractive.js. I didn't remove the polyfill file, since that might cause errors for people that have a merged CDN link. It now just prints a message to the console that it is no longer needed, and it will be completely removed for 1.0.

**Pull request merged**
