### PR TITLE
fix various splice-related bugs

### PR DESCRIPTION
**Pull request by Rich-Harris**
see #1742 for background

### CODE REVIEW

**Comment by evs-chris** [comment]
:+1: LGTM!

**Comment by martypdx** [comment]
Soo is the `{{foo.0}}` case fixed because of the `touchedFrom` or the `ReferenceExpressionResolver` bug (the later wouldn't make any sense to me, but just checking...)?

**Comment by Rich-Harris** [comment]
Yep, `touchedFrom` - `foo.0` is being notified correctly now

**Comment by evs-chris** [comment]
Should be the `touchedFrom` because without it, only the last index (or indices if you `unshift`ed multiple things) would get `mark`ed.

**Comment by Rich-Harris** [comment]
Can either of you remember the history to `noCascade`? While looking into this whole thing just now, I removed it without any tests failing. Is it doing something important performance-wise that isn't represented in the test suite?

**Comment by evs-chris** [comment]
I think it predates my time, but it looks like it was originally intended to keep computations from running multiple times (see `applyChanges`). I remember there being a comment speculating that it was no longer necessary since computations are lazy now?

**Comment by Rich-Harris** [comment]
In which case I'm tempted to remove it... any thoughts @martypdx?

**Comment by martypdx** [comment]
Introduced via #1282, `noCascade` keeps [`applyChanges`](https://github.com/ractivejs/ractive/blob/dev/src/viewmodel/prototype/applyChanges.js#L35) from cascading down into the computations dependent on the properties of the array item (because it was just an array modification).

**Comment by Rich-Harris** [comment]
@martypdx thanks, good sleuthing. The test added in #1282 ('Array elements removed via *action* do not trigger updates in removed sections') is still green, so maybe @evs-chris was right about lazy computations?

**Comment by martypdx** [comment]
> so maybe @evs-chris was right about lazy computations

Functionally yes. But lazy computations aren't completely free. What if it's an object with many expressions under it? I'd try the box update perf test with and without to get an idea of impact (if any) of one computation/expression.

**Comment by Rich-Harris** [comment]
There's no difference between with `noCascade` and without in the case of the box test. Best thing is probably to leave it out of this PR and I'll create a separate issue, we can try and get a definitive answer later. Will merge this and #1795

**Pull request merged**
