### PR TITLE
Name bound checkboxes with duplicate values and crossing component boundaries - #2163

### LINKED ISSUE #2163: Two-way binding only works within a single instance of component
Two-way data binding correctly only works within a single instance, not across component boundaries ([live demo](http://jsbin.com/qepupayego/1)).

Question from [stackoverflow](http://stackoverflow.com/questions/32755097/two-way-binding-doesnt-work-inside-ractive-components).

### PR DESCRIPTION
**Pull request by evs-chris**
Named checkbox bindings where more than one checkbox shared a value were not handled. This adds support for them. It also moves the group registry from a private object in binding group onto a property of the model so that components are guaranteed to get the same group if they share a model even if mappings or some other factor make the hash not equal. This should fix #2163.

I'm 99% sure this is correct, but I would like a sanity check on both functionality and construction.

I removed the RadioBinding TODO to move to binding group because they have no model in which to store the group.

### CODE REVIEW

**Comment by heavyk** [comment]
awesome dude! this fixed another tiny issue for me on edge. great work

**Comment by JonDum** [comment]
@evs-chris is killing it so hard lately. Do you have a git tip or something man?

**Comment by martypdx** [comment]
> I removed the RadioBinding TODO to move to binding group because they have no model in which to store the group.

But the browser handles the "linkage" so it works in components, right? :D http://jsfiddle.net/x3w18j13/

**Comment by evs-chris** [comment]
@martypdx It works in this branch... or did I misunderstand your question?

**Comment by martypdx** [comment]
@evs-chris just did fiddle to prove it works and sort things out in my mind, thx!

**Pull request merged**
