### PR TITLE
Improve parser performance

### PR DESCRIPTION
**Pull request by MartinKolarik**
Reduces the parse time by about 800%.

### CODE REVIEW

**Comment by Rich-Harris** [comment]
jaw-drop

That's... amazing. Travis seems to be [complaining](https://travis-ci.org/ractivejs/ractive/builds/84717171) about `npm run build`, any ideas why?

**Comment by MartinKolarik** [comment]
Looking at it right now.

**Comment by MartinKolarik** [comment]
I forgot to run the tests after the last change. Now fixed - performance remains the same.

**Comment by JonDum** [comment]
> 800%

Holy moly that's quite the improvement. All that from caching some RegExps?

**Comment by Rich-Harris** [comment]
:cocktail:

**Comment by MartinKolarik** [comment]
> Holy moly that's quite the improvement. All that from caching some RegExps?

Mostly from using them instead of several `String#indexOf()` lookups. Caching was just a little bonus.

**Pull request merged**
