### PR TITLE
ISNIT0-2535 Lazy Attribute now supports dynamism

### PR DESCRIPTION
**Pull request by ISNIT0**
**Description of the pull request:**
I have added a middleman which intercepts input and keyup events on all elements, it then checks for laziness every time an event is fired. This may not be the best way, but It's the most sensible I can find with my limited knowledge of the codebase.

Tests included!

**Fixes the following issues:**
Issue #2535

### CODE REVIEW

**Comment by ISNIT0** [comment]
I don't think that failing build is my fault?

**Comment by evs-chris** [comment]
That is a reasonable approach. This is also one of the things covered by #2369 in a slightly different way.

Did you run a build locally (`npm run build`)? Phantom is pretty sensitive about async input tests, but it looks like there are two that are actually broken. I'm not sure about the failing observer test (but I hate that test... it's a tricky one to keep green :smile:), but for the twoway one, `0` is considered `true` because `<input lazy />` results in `lazy === 0`.

**Comment by ISNIT0** [comment]
@evs-chris Just saw your comment, I originally didn't realise the defaults, but just updated the PR :)

**Comment by evs-chris** [comment]
This is now available in edge :smile:

**Pull request closed without merging**
