### PR TITLE
BREAKING CHANGE: change promise rejection handling behaviour (#1788)

### PR DESCRIPTION
**Pull request by Rich-Harris**
See #1788. With this PR, asynchronous errors that happen inside `.render()` and `.animate()` aren't dealt with by Ractive, but must be dealt with by a `.catch()` handler, regardless of `Ractive.DEBUG`.

The exception is an automatic render (i.e. where `new Ractive()` is passed an `el` property, or it's an inline component) because then there's no way for the developer to get hold of the promise. In that case, if `Ractive.DEBUG_PROMISES` is `true` (the default), a message/stack will be logged:

screen shot 2015-03-14 at 9 58 34 am

### CODE REVIEW

**Comment by martypdx** [comment]
Are there browsers that have native implementations that Ractive would use to that don't handle errors sufficiently?

**Comment by Rich-Harris** [comment]
AFAIK it's only Chrome that logs uncaught errors (so far) - in other browsers they'll get swallowed. So if you do this in Firefox or Safari...

```js
ractive.set( 'foo', 'somethingThatWillCauseAnErrorSomehow' );
```

...then in theory you'd need to add a `.catch()` handler. In practice though a) I'm *fairly* sure that anything that could cause an error inside those promise-returning methods would happen outside the promise itself, so the error wouldn't get swallowed, and b) we couldn't do anything in these situations anyway:

```js
ractive.set( 'foo', 'somethingOkay' )
  .then( throwAnError );
```

**Comment by martypdx** [comment]
I just wonder if we could simplify the default logic to: `Ractive.DEBUG_PROMISE = Ractive.DEBUG && !hasNativePromises;`

**Comment by Rich-Harris** [comment]
Surely that would just mean that Firefox et al wouldn't get the extra debugging help if initial render failed? If there was a way to detect whether the browser printed unhandled promise rejections, that'd be ideal, but AFAICT there isn't a way to do that, hence erring on the side of verbosity.

**Comment by Rich-Harris** [comment]
will merge for the sake of 0.7 - we can revisit the details in future if we decide we got them wrong

**Pull request merged**
