### PR TITLE
Make inline partials behave the same with new Ractive() or Ractive.extend()

### PR DESCRIPTION
**Pull request by Rich-Harris**
**not ready for merge**

See #1679

### CODE REVIEW

**Comment by evs-chris** [comment]
The component finding code doesn't look at the constructor for components, which makes the partials get stuck to the wrong part of the template. Quick fix?:

```diff
--- a/src/parse/converters/partial/processPartials.js
+++ b/src/parse/converters/partial/processPartials.js
@@ -31,7 +31,7 @@ function getComponent( path, item ) {

        if ( item.e ) {
                for ( i = 0; i < path.length; i++ ) {
-                       if ( cmp = ( path[i].components || {} )[name] ) {
+                       if ( cmp = ( path[i].components || path[i].constructor.components || {} )[name] ) {
                                return cmp;
                        }
                }
```

I have this as a commit with a test with an extra, more deeply inherited set of components for good measure if you'd like me to push it.

**Comment by Rich-Harris** [comment]
@evs-chris totally missed this, sorry - do you still have that test/commit lying around?

**Comment by evs-chris** [comment]
I do. I pushed it, supposing that's why you asked :)

**Comment by Rich-Harris** [comment]
Neato. Thanks!

**Pull request merged**
