### PR TITLE
work around 6to5 transpilation issue

### PR DESCRIPTION
**Pull request by Rich-Harris**
fix for #1654?

### CODE REVIEW

**Comment by evs-chris** [comment]
I _think_ I tried that and 6to5 still helpfully converted it to the "better syntax". You may have to do something sillier like
```js
var specials = [];
specials[ 'true' + '' ] = true;
specials[ 'false' + '' ] = false;
specials[ 'undefined' + '' ] = undefined;
specials[ 'null' + '' ] = null;
```

**Comment by evs-chris** [comment]
Ah yes, the original PR, which _almost_ worked, used this method and still got mangled was #1595. To all of those out there supporting IE8 (myself included), I am deeply sorry, and not just because I broke the legacy build trying to fix the legacy build :)

**Comment by Rich-Harris** [comment]
Building it locally just now gave me this result:

```js
specials = {};

specials["true"] = true;
specials["false"] = false;
specials.undefined = undefined;
specials["null"] = null;
```

Which is okay, because `undefined` isn't a keyword. Maybe 6to5's behaviour changed... @sebmck, @thejameskyle any chance you can shed any light on this? Can you recall if 6to5 started quoting keyword property names at some point? I did a quick issue search but couldn't find anything obvious.

**Comment by sebmck** [comment]
@Rich-Harris 6to5 has been quoting member expression keywords since 1.12.14. I'm not sure I completely understand the issue.

**Comment by evs-chris** [comment]
LGTM. It looks like I most likely had 1.14.4 when I attempted that fix. I probably just did something wonky.

**Pull request merged**
