### PR TITLE
BREAKING: integer literals are probably not a reference - #2397

### PR DESCRIPTION
**Pull request by evs-chris**
This is a breaking change in that this specific case is no longer supported `{{#with someArray}}{{1}}{{/with}}`. There was a bug with the original support for that anyways that let numbers ending in `0` slip through as expressions.

If for some reason the original behavior is needed, it can be had with `{{#with someArray}}{{this[1]}}{{/with}}` or some more terse equivalent.

Any objections?

### CODE REVIEW

**Comment by fskreuz** [comment]
Unless I'm missing anything obvious, :+1:

**Comment by martypdx** [comment]
Intra-reference numbers like `{{ this.1 }}` are also okay?

**Comment by evs-chris** [comment]
Yes, non-number-literal numbers take a different path as references, so `this.1` is still valid. Only places where just a number literal is parsed are affected.

**Comment by heavyk** [comment]
what about `{{.1}}`?

I'm also :+1:

**Comment by evs-chris** [comment]
`{{.1}}` is the same as `{{0.1}}` because numbers. I think that's always been the case, but then again I always write the leading `0`.

**Comment by heavyk** [comment]
you're right. I just tried it for myself. I also always write the leading 0 for numbers, but I did try it for index access once in a loop and it didn't work. (seems obvious now)

I think that `{{0}}` is confusing to begin with.

**Comment by fskreuz** [comment]
> {{.1}} is the same as {{0.1}} because numbers

So this means `{{ .1 }} !== {{ this.1 }}`? Hmm... a potential gotcha.

**Pull request merged**
