### PR TITLE
Legacy removal

### PR DESCRIPTION
**Pull request by ghost**
**Description of the pull request:**

Bring-your-own-polyfill is the name of the game. Removes built-in polyfills and shims. 😄 

**Is breaking:**

API: yes
- `Ractive.Promise` removed.

Browser support: yes.
- ES5 polyfills removed.
- `requestAnimationFrame` polyfill removed.
- Promise polyfill removed.

Recommended IE version: 10

Shims/polyfills required if on a totally old browser:
- ES5 shim
- ES6 shim (or at least a Promise shim)
- rAF polyfill

**Fixes**

- https://github.com/ractivejs/ractive/issues/1636

**Reviewers:**

If you're reading this, I encourage you to do so. 😅

### CODE REVIEW

**Comment by evs-chris** [comment]
Big :+1: for 0.9. :clap:

**Comment by tomekmarchi** [comment]
Image of iRuvU

**Comment by kouts** [comment]
So what will happen to Ractive.Promise? Will it continue to work or do we have to change code that refers to Ractive.Promise with something else?

**Comment by ghost** [comment]
At the moment, the PR removes `Ractive.Promise` in favor of (and to encourage the use of) the native `Promise`. You will have to switch to using the native `Promise`, shim when necessary. It should just be a simple Find All and Replace from `Ractive.Promise` to `Promise`. Should you want to keep use of `Ractive.Promise` to avoid a huge Find All and Replace, the following should do:

```
Ractive.Promise = Promise;
```

As far as I know, the built-in Promise was standards-compliant so there shouldn't be any issues.

Notable platforms that don't do native promises yet include IE11, PhantomJS and Android <= 4. https://kangax.github.io/compat-table/es6/

**Comment by evs-chris** [comment]
This looks like it's done and ready to merge?

**Comment by ghost** [comment]
@evs-chris  It's ready. You can merge it if good. 😄

**Comment by tomekmarchi** [comment]
@evs-chris When will this be applied? Dying for this speed improvement and size decrease babe.

**Comment by evs-chris** [comment]
Now. :smile:

It might not be an awful idea to put together a ractive-polyfills project that makes it easier for those stuck supporting ie9 and friends, bless 'em. We have the code sitting around, though it's now only in history.

**Comment by tomekmarchi** [comment]
@evs-chris They are traitors to the cause I'd say.

**Pull request merged**
