### PR TITLE
More robust . escaping

### PR DESCRIPTION
**Pull request by MartinKolarik**
This PR addresses the following issues:

1. Multiple escapes in a single keypath - `ractive.get('foo\\.bar\\.baz')` now works correctly (was interpreted as `ractive.get('foo\\.bar.baz')` before).

2. `{{foo['bar.baz']}}` updates on `ractive.set('foo.bar\\.baz')`

3. `$`'s in keypaths aren't incorrectly converted to `.`

4. Backslashes can also be escaped, so calling `ractive.set('foo\\\\.bar', 1)` is the same as `ractive.set({ 'foo\\': { bar: 1 } })`

### CODE REVIEW

**Comment by evs-chris** [comment]
1 & 2. Well dang.
3. Sorry, I completely forgot that `$` is legal in an identifier in JS.

Thanks for cleaning up the stuff I missed :)

**Comment by Rich-Harris** [comment]
I've merge dev back into this branch to make it mergeable – unfortunately one of the tests is failing on `npm run build`. Not able to look into it right now, @MartinKolarik @evs-chris any ideas?

**Comment by MartinKolarik** [comment]
>unfortunately one of the tests is failing on npm run build

Hmmm. All tests are passing when I run them locally.

**Comment by evs-chris** [comment]
It dies on me from the console, but works fine in the browser. I'm going to try to test it directly in node and see what happens.

**Comment by MartinKolarik** [comment]
>All tests are passing when I run them locally.

Actually, `npm test` works fine, but `npm run build` fails for me as well..

**Comment by evs-chris** [comment]
It also works fine when run directly in node. I'm at a loss... commenting out the last part of offending test passes the build.

**Comment by MartinKolarik** [comment]
Looks like it has something to do with magic mode.

**Comment by evs-chris** [comment]
Sheesh... finally found it, thanks to @MartinKolarik pointing in the right magical direction.

**Comment by MartinKolarik** [comment]
@evs-chris :+1:

**Comment by heavyk** [comment]
you guys are on fire!

**Pull request merged**
