### PR TITLE
Better detection of existing keys in models

### PR DESCRIPTION
**Pull request by NikhilVerma**
See issue #2191

### CODE REVIEW

**Comment by evs-chris** [comment]
Out of curiosity, and I have no idea the performance implications here, why not replace the `hasProp` const with
```js
function hasProp(prop) {
  return prop in this;
}
```
?

**Comment by Rich-Harris** [comment]
Thanks @NikhilVerma! @evs-chris `prop in this` checks the whole prototype chain rather than own properties. In fact my initial thought was 'why don't we just use `prop in value` instead of ascending the constructor chain?', but of course that fails when you have property names that clash with e.g. `Array.prototype`, as in this scenario...

```html
{{#each items}}
  {{#each some}}...{{/each}}
{{/each}}
```

```js
items: [{ some: 'a' }, { other: 'b' }, { some: 'c' }]
```

...whereby the second iteration picks up the `items` array's `some` method, which we definitely don't want. Took me some headscratching to figure out why that test was failing when I tried `prop in value`...

**Comment by evs-chris** [comment]
Hadn't considered that at all... @NikhilVerma Nice!

**Comment by NikhilVerma** [comment]
Awesome :D

**Comment by martypdx** [comment]
btw - We might eventually want to use `getPrototypeOf` instead of walking the constructor chain. We need it for babel classes anyway on ie8.

I tested out [this polyfill](https://github.com/es-shims/es5-shim/blob/master/es5-sham.js#L53-L81) on ie8 and seemed to work fine.

**Pull request merged**
