### PR TITLE
Event-ish refactor: suspendable listeners and this. namespaced events - RFC

### PR DESCRIPTION
**Pull request by evs-chris**
## Description of the pull request:

This does a few different-yet-related things:

### Silence-able observers

There's been an open issue for a while requesting the ability to temporarily stop observers from firing  (#1182), so this adds `silence()`, `isSilenced()`, and `resume()` methods to the handle returned from `ractive.observe()`. I went with `silence` over `pause` or `suspend` because the observer still gets changes, it just doesn't fire the notification.

This could conceivably be extended to `cork`-like functionality where changes are stashed until `uncork`ing (probably with `resume` too) or a different form of `silence` where the observer ignores notification, and thus, keeps the old value in place for future `resume`. All of that seems a bit YAGNI for now though, whereas built-in locking for observers would be handy in a number of pretty common scenarios. Opinions?

### Silence-able events

Similar to observers, there's been a request around for a while to temporarily stop events from firing (#2323), so this adds the same `silence()`, `isSilenced()`, and `resume()` methods to the handle returned from `ractive.on()`. Again, I went with `silence` because nothing is torn down while the listener(s) is silenced; they just don't fire. It also mirrors the observer version nicely.

### Event listener other stuff

This also fixes a bug with multiple events subscribed with the same listener at the same time e.g. `this.on('foo bar baz')` wherein the returned handle's `cancel()` method wouldn't actually cancel anything.

It also refactors the `on()` method to be a bit less branchy, like the recent `observe()` refactor.

### Events with an initial implicit `this` namespace

One of the things that seems to be a bit counter-intuitive when first dealing with event bubbling is that `ractive.on('foo')` and `ractive.on('*.foo')` won't both be triggered by `ractive.fire('foo')` (#2566). It seems that the general assumption is that `*.foo` means all the `foo`s, which makes sense to me too. So this adds an implicit `this.` namespace to all intial events, meaning that `ractive.fire('foo')` will trigger any of these listeners: `foo * this.foo *.foo this.*`. It notably _won't_ fire `*.*` because that would mean that any lifecycle events would start triggering `*.*` listeners. That may not be a bad thing, but it breaks tests. I'm not sure that it's intuitive behavior, and I can't really see how all-wild listeners are particularly useful anyways. Opinions?

I really wasn't aware of this before I started poking around this code, but you could already fire namespaced events on your own by using names with `.`s in them. Given that, I considered adding `**` flavors of listeners that would "consume" multiple path segments in the `**` portions, but for now that seems a bit YAGNI too. Again, opinions?

This refactor also (kinda) removes one of the vestiges of versions < 0.8, - the star map. The star map helpers were only used by events as of 0.8, as the Model family took over the matching of wildcard keypaths. The star map helpers basically create a cartesian product of a keypath and an equal-length all-star keypath ( `a.b.c` <-> `*.*.*` ), which is still needed for finding matching event listeners. So there's now a slightly simplified, still-caching (since they're not exactly cheap to create and lifecycle events mean that they're not exactly rare - I'm looking at you `change`) version of star maps moved into the event firing code.

## Fixes the following issues:
#1182 #2323 #2566 #1458

## Is breaking:
Kinda sorta. If you were relying on `foo` and `*.foo` listeners catching only `this` instance events and only child component events respectively, this is breaking. Otherwise, which seems to be the more intuitive assumption based on issues and SO questions, this would actually be a bugfix. If `*.foo` _must_ only be triggered by child events, you can now check the source ractive against `this` to be sure they're different.

## Reviewers:
Yes, please.

### CODE REVIEW

**Comment by mefjuu** [comment]
It seems that subscribing multiple events as object map fixes https://github.com/ractivejs/ractive/issues/1458 also.

**Comment by evs-chris** [comment]
@mefjuu it does now :smile:.

I've added changes to resolve #1458:

### Events hash

With this, you can specify an `on` hash in your options that takes key/value pairs. The keys may be anything that's valid to pass to `ractive.on()`, so you can stick the same handler on multiple events with a space separated list e.g. `'foo bar baz.bat'`. The values may be functions or an object with a `handler` function and other options. At this point "other options" for events is just `once: true`, which subscribes the event using `ractive.once()` instead of `ractive.on()`.

Components/extended instances _add_ to their parent event hash, so

``` js
const cmp = Ractive.extend({ on: { foo() { ... } } });
const r = new cmp({ on: { foo() { ... } } });
r.fire('foo');
```

will trigger the foo methods from both configs. The reasoning behind this is that the `cmp` component set the handler up for a reason, and as such, it should not be overridden accidentally by an extension or instance. Handlers are installed from root component to instance, so the root handlers are called first. If necessary, we could specify that one of these listeners returning `false` would halt the subscriber notification, but I don't think that will really come up.

### Observers hash

As with events, you can specify an `observe` hash in your options that takes key/value pairs. Like events the keys can be any string that can be passed to `ractive.observe()`. Also like events, the values may be a function or an object with a `handler` function and additional options. Here's an example with each:

``` js
new Ractive({
  observe: {
    foo() { /* I will fire at init as the observer initializes */ },
    'bar baz': {
      handler() { /* I will not fire at init, and I will not fire until dom manipulation is done */ },
      init: false,
      defer: true
    },
    bat: {
      handler() { /* I will only fire once when bat first changes */ },
      once: true
    }
  }
});
```

As with events, the observer hash is additive, so base component observers and instance observers are all subscribed, with the base observers subscribing first.

**Comment by ghost** [comment]
Yasss! Events hash! I remember requesting that one. Few questions:
- I assume `events` and `observers` are taken names already? Would be more intuitive though.
- Can lifecycle events be put there? Or are those specifically for user-defined events?
- I encountered `this._super()` while reading the components docs. It appears to be used by lifecycle events to call overridden parent lifecycle events. Would it make sense to do the same for regular events?

And a few other things:
- A warning as to why `*.*` is not supported might be good though.
- Starmap... the code that generates all possible combinations of keypaths given a starred keypath? 😁

**Comment by evs-chris** [comment]
1. `events` is taken. I went with `on` and `observe` because they match the method name, and it seemed fitting as they are _just_ shortcuts for calling `on` and `observe` after the `config` event fires.
2. Any old event can be here, including lifecycle and wildcard.
3. I think the `_super()` is only for dealing with the `onwhatever` method flavor of event handling. With this, that stuff could actually go away. Even if you don't call `this._super()` in an `onwhatever` method, the event will still trigger an listeners that super may have installed.
4. Warn about not supporting it, or just don't special-case it and note it as a breaking change?
5. Well sort of :smile:. It's all possible matching starred keypaths for a given absolute keypath. The star map for `a.b.c` is `[ 'a.b.c', '*.b.c', 'a.*.c', 'a.b.*', '*.*.c', '*.b.*', 'a.*.*', '*.*.*' ]` - or the cartesian product of `a.b.c` and `*.*.*`. It's used when a namespaced event fires, say `foo.bar`, to find any listeners that could match, so when you have `ractive.on('*.bar', ...)`, the `foo.bar` event will call that listener.

**Comment by evs-chris** [comment]
Addenda:
1. I also went with `on` and `observe` to keep them consistent _because_ `events` is taken.
2. Any old event, except things that take place on or before `onconfig` :smile:. I _think_ I could move the subscription point to just before `onconstruct`, but I would probably have to split events and observers up. Should I do that?

**Pull request merged**
