### PR TITLE
Remove support for unresolved references - RFC

### PR DESCRIPTION
**Pull request by evs-chris**
## Description of the pull request:
This removes the unresolved references checks that work like this:
1. If a matching reference cannot be found in available contexts or keypaths, register a callback with each potentially matching path
2. Each time data is set, the model checks its list of unresolveds to see if there's a listener that is interested in the data
3. When the callback is fired, it should also remove itself from other registered paths
4. The reference is now resolved.

This is one of those features that is really nice in theory, but in practice can cause weirdness, confusion, and bad performance, which is why it's also against recommended practices. _Only_ ambiguous references can end up in the unresolved queue.

This replaces the above process with this one:
1. If a matching reference cannot be found in available contexts or keypaths, resolve the reference as if it were relative against the current context.

From what I've seen, a large percentage of refs that end up in the unresolved queue end up being resolved in their current context anyways.

**Note:** this is not removing support for ambiguous references. Those will still resolve to the closest matching context as they would before. It just stops ambiguous references from going on unresolved until some data is added somewhere along their context hierarchy that matches their base key (`foo` in `foo.bar.baz`).

I only had to remove or modify 11 tests to get this passing, and a couple of those were tests for warnings about ambiguous references in bindings.

## Fixes the following issues:
Part of #2798 

## Is breaking:
Yep

## Reviewers:
Yep

### CODE REVIEW

**Comment by aharpervc** [comment]
This still works, right?

```js

const MyComp = Ractive.extend({
// ...
});

const my = new MyComp({
  el: '#target',
  template: '{{ wut }}',
  data: {
    idk: "??",
  },
});

my.set("wut", "all good");
// and "all good" is rendered into the dom
```

**Comment by evs-chris** [comment]
Yes, because when `wut` isn't found, it ends up resolving to the `wut` key on the context, which happens to be the root context. If the template was `{{#with something}}{{wut}}{{/with}}` with `{ something: {} }` as data, then `my.set('wut', 'all good')` would not have any effect because the context for the interpolator is `something` rather than root. Behavior in 0.8 and edge right now would still render "all good" because of the unresolved process. The `something` in data is required so that the `with` will render.

**Comment by aharpervc** [comment]
Ok, thanks for clarifying

**Comment by evs-chris** [comment]
Any objections to this? _I_ don't think that actual unresolveds happen too often in the wild because you're usually interested in the current context when it eventually pops into existence. I'd like to have this out for the alpha cycle (beta? rc? not sure what best to call it) for 0.9 so that I can get some more general community feedback.

**Comment by ghost** [comment]
So...

- The "climbing" behavior will still stay.
- Immediately resolve (to the current context) if reference is not found anywhere.

I'm not exactly clear what resolution actually involves. Does it lock in the keypath to the current context? Does that mean "climbing" only happens during the first time a reference tries to resolve?

So in the case of this removed test:

	test( 'Data is synced as soon as an unresolved mapping is resolved', t => {
		onWarn( () => {} ); // suppress

		const ractive = new Ractive({
			el: fixture,
			template: '<Outer/>',
			data: {
				item: { x: 1 }
			},
			components: {
				Outer: Ractive.extend({
					template: '{{#with item}}<Inner foo="{{foo}}"/>{{/with}}'
				}),
				Inner: Ractive.extend({
					template: '<p>foo: {{foo}}</p>'
				})
			}
		});

		t.htmlEqual( fixture.innerHTML, '<p>foo: </p>' );

		ractive.toggle( 'item.foo' );
		t.htmlEqual( fixture.innerHTML, '<p>foo: true</p>' );

		ractive.toggle( 'item.foo' );
		t.htmlEqual( fixture.innerHTML, '<p>foo: false</p>' );
	});

The only way to render `foo` is to set in on `<Outer/>` (which then maps it to `<Inner/>`) or set it on `<Inner/> directly?

**Comment by evs-chris** [comment]
Any time a reference resolves, it locks in the resolved absolute keypath. The only way to change it would be to cause an unbind/bind, which can be accomplished by toggling a conditional section off and back on. That is still the case here, but instead of waiting for the reference to appear up the context hierarchy, it just locks onto the current context. This _only_ affects ambiguous references, so any prefixed refs, like `.foo`, `../../bar.baz`, and `~/bar` are not affected.

~~For the `foo` question, yes. I think that can be addressed though, by having mappings resolve in their parent context. Actually, I'm wondering why they don't already...~~ They do, so never mind. That test was removed erroneously.

**Comment by evs-chris** [comment]
Turns out I removed that test erroneously. I have reinstated it along with a working version of the explicit mapping test, which was just lacking the explicit mapping on the first component.

**Comment by sarendipitee** [comment]
Looks good to me. Looks much simpler with little drawback.

**Comment by PaulMaly** [comment]
Very bad idea, sad. (((

**Comment by kouts** [comment]
This I think is quite dangerous in running projects, can something like a warning be added?

**Comment by evs-chris** [comment]
There is a warning flag [`warnAboutAmbiguity`](https://ractive.js.org/api/#warnaboutambiguity) that will give you a console warning any time a reference doesn't resolve to an immediate context. That will also warn you on references that exist in a parent context, but it should be enough to get an idea of what needs to be stubbed out in data to avoid issues with unresolveds removal.

If you're loading data asynchronously and using non-isolated components, you can stub out the data to avoid resolving in the wrong context e.g. `new Ractive({ data: { foo: { bar: {} }, baz: {} } })` if your components are expecting to be able to access `foo`, `foo.bar`, and `baz` on the parent at some point.

I'm sorry that removing unresolveds broke your workflow. I do still see it as necessary due to the number of very buggy corner cases caused by unresolveds, two-way binding, and shuffling.

**Comment by ghost** [comment]
I remember the days in Angular where I end up wasting my time "scope hunting" - hunting for the scope of some variable, only to find out it actually lives 5 controllers above it, which may or may not exist at times, and is operated by totally unrelated code which can be pulled out at moments notice.

Having a framework that enforces encapsulation/isolation and explicit mapping of data by default is very helpful.

**Pull request merged**
