### PR TITLE
add notes on reporting security vulns

### PR DESCRIPTION
**Pull request by Rich-Harris**
We got a black mark on a security report (see #1897) for not having a security response program. As a starting point, we should make it clear that people are encouraged to report security vulnerabilities, and by asking people to add `[security]` to issue titles we can ensure they're appropriately prioritised.

One thing this *doesn't* give us is a way for people to report vulnerabilities privately. Is that something we also need to consider?

### CODE REVIEW

**Comment by MartinKolarik** [comment]
I think vulnerabilities (although I don't expect there to be many) should be always reported privately.

**Comment by Rich-Harris** [comment]
@MartinKolarik yeah, I guess you're right.

Any opinions on how we make that work? Does one person volunteer to be the point-of-contact for these reports, with their email address in CONTRIBUTING.md, or do we set up an email address for the core team? Bearing in mind that reports are likely to be infrequent.

**Comment by Madgvox** [comment]
If they're likely to be infrequent, I don't think it'd be too big a hassle to have one person take the initial message and then loop everyone else into the thread manually. That said, if creating a mailing list would be easy to set up, that'd be the better option for sure.

**Comment by MartinKolarik** [comment]
Having only one person as the point-of-contact could be a problem if they become temporarily unavailable for any reason. I can set up an email address with forwarding to the members of the core team.

**Comment by Rich-Harris** [comment]
@MartinKolarik that'd be great, thank you. You're right on all counts

**Comment by MartinKolarik** [comment]
Turns out Google groups can also be private, so I set up one instead of a regular email account. @ractivejs/team-ractive members, please request an invitation [here](https://groups.google.com/forum/#!forum/ractive-js-security).

Only members can see the messages sent to the group. Note that when somebody sends a report, you need to cc them when responding.

**Comment by Rich-Harris** [comment]
@MartinKolarik thanks :email: :closed_lock_with_key: :+1:

**Comment by Rich-Harris** [comment]
Have amended [README.md](https://github.com/ractivejs/ractive/blob/security/README.md#reporting-security-vulnerabilities) and [CONTRIBUTING.md](https://github.com/ractivejs/ractive/blob/security/CONTRIBUTING.md#reporting-security-vulnerabilities) with the email address - have I missed anything?

**Comment by MartinKolarik** [comment]
@Rich-Harris looks good.

**Pull request merged**
