### PR TITLE
Wrap animateStyle css transitions in a timeout in case transitionend doesn't fire - #2463

### PR DESCRIPTION
**Pull request by evs-chris**
**Description of the pull request:**
This adds a timeout of `duration + (delay || 0) + 10` to css transitions in `animateStyle` to force the transition to complete within 10ms of its target. `transitionend` events appear to not be particularly reliable in scenarios where you trigger transitions like a madman.

After aiming the fiddle from #2463 at a build of this branch and about 5 minutes of vigorous mouse wiggling, I'm reasonably confident that this will take care of transition-event-related orphan nodes. I'll probably go ahead and merge this later this afternoon (once it goes green) so that others can get their wiggle on as well to make sure I'm not experiencing the placebo effect.

Side note: I have an idea for a subscription-based software shake weight competitor...

**Fixes the following issues:**
Hopefully #2463

**Is breaking:**
No

### CODE REVIEW

**Comment by evs-chris** [comment]
I did another set of wiggle tests before and after this, and the before left stuck elements where the after didn't. @JonDum, of you have a few minutes, can you see if you can get it to break again?

**Comment by JonDum** [comment]
Looks good now! 93682182ec38 seemed to do the trick.

lol

Still looks hilarious, but that's what I would expect. The important part is that it's not leaving any orphans! 👍

**Comment by evs-chris** [comment]
Thanks! 🎉

**Comment by sabob** [comment]
There is a slight issue with this setTimeout when render/teardown ractive instances.

I use ractive as the view in a single-page app, with a menu  for switching between ractive views. When switching I unrender/teardown the previous view and render the new one. This is done using a fade effect.

Here is the fiddle:
http://jsfiddle.net/sabob/q2j22hL5/2/

Quickly click twice on the "Change view" button and notice the counter appears, then disapears as the timeout kicks in. If I remove the "cssTransitionsDone()" from the timeout, it works as expected. 

I think the timeout should also be cleared when the view is unrendered?

**Comment by evs-chris** [comment]
@sabob I've been playing with this a bit, and I'm not certain exactly how things are interacting poorly here. The elements stick around, but the interpolator is not. I have some changes that add better transition cancellation to the unrender, but I'm having a hard time with a test to verify that it solves the problem.

**Comment by evs-chris** [comment]
Turns out I was overthinking it...

@sabob, it seems to be much less frequent, but there is definitely something in the render process that doesn't like to have instances unrendered while they're still transitioning in. Was it also happening some before?

**Comment by sabob** [comment]
@evs-chris still happens after complete queue code. Doesn't happen in 0.7.3 or without the cssTransitionsDone line in the timeout.

In case you cannot produce the error here is a gif showing the issue. Clicking the button twice updates the counter to 2, then the counter disappears.

animate

**Comment by sabob** [comment]
In a future release it would be great if there is a way to stop/start the animations, I've created a issue for this awhile back:

#1551

**Comment by evs-chris** [comment]
Found it. Basically, a new instance was being torn down before it was rendered, and rendering the torn down (and thus unbindable) interim instance was causing the new, correct instance to be torn down. I've added a check for render on a torn down instance. It will now throw out a warning in debug mode and roll on without breaking stuff.

**Comment by sabob** [comment]
Thanks Chris, seems to work now. 

From your explanation that ractive tears down before render, why does that occur? Is it because animations turns things asynchronous?

**Comment by evs-chris** [comment]
Pretty much, yes. It's the combination of transition asynchrony and triggering an additional round of callbacks before the previous round has completed.

**Comment by sabob** [comment]
Perhaps in a future release things could be more robust if render cancels current active intro/outro animations on the ractive instance. This will turn things back into synchronous mode.

On the other hand maybe I'm naive and there are use cases for the current behavior...

**Comment by evs-chris** [comment]
Unfortunately, once it's gone asynchronous there's no coming back, and I think transitions are pretty much required to be async.

In this particular case, you could side-step the issue by keeping the latest promise around to make sure you don't step on another transition by triggering a render during an outro. At that point, the user would experience some lag when rapid-fire clicking, but there's no opportunity to damage rendering.

```js
// next to oldRactive declaration
var promise;
//...

if (oldRactive == null) {
    promise = (promise || Promise.resolve()).then(() => newRactive.render('main'));
} else {
    promise = promise.then(() => oldRactive.teardown().then(() => newRactive.render('main')));
}

oldRactive = newRactive;
```

Though with the teardown and render guards, I think it's pretty safe to do what the fiddle is doing. Unless you're depending on component render hooks to side-effect somewhere. Then your only option is to keep the promises around somewhere to ensure that all instances actually get rendered.

**Pull request merged**
