### PR TITLE
ES6 APIs pre-polyfilled

### PR DESCRIPTION
**Pull request by ghost**
## Description:

- `Promise`, `array.find` and `Object.assign` now pre-polyfilled on main build.
- `polyfills.js` still being shipped for older, pre-ES5 browsers.

## Fixes the following issues:

Many, mostly comments on various post-removal issues.

## Is breaking:

Shouldn't be.

## Reviewers

@dagnelies @MartinKolarik @sabob @evs-chris and others who I cannot tag because Github.

### CODE REVIEW

**Comment by MartinKolarik** [comment]
IMHO the point of #3026 was to have only polyfills needed for IE 11 directly in the regular build, which was the case before #2801. I personally don't care about older IE versions, which are officially marked as unsupported by MS, and don't want to load polyfills for ES5 features (e.g. `Array#forEach` and friends), but I think ES6+ polyfills should be included by default for some time.

For all polyfills you can just use https://cdn.jsdelivr.net/combine/npm/ractive/polyfills.min.js,npm/ractive/ractive.min.js, which is also linked in the docs.

**Comment by dagnelies** [comment]
Thanks!

**Comment by dagnelies** [comment]
Ah, I was a bit quick in my answer since I was in a hurry. I completely agree with what @MartinKolarik said, IE 11 should be supported in the default for some time. The adequate polyfills for it should be in the standart release.

Btw, IE 11 is not EOL as stated in #2801. It's older IE < 11 that are EOL since 2016.

**Comment by ghost** [comment]
Updated PR. Build updated with `Promise`, `Object.assign` and `array.find` polyfilled out of the box. Ractive still requires at least ES5 to work, but the polyfills file is still there should there be a dire need to support really old platforms. 🎉  

Aaand re-removed the all-in-one legacy.js. Unless someone really wants a fully-polyfilled build, lemme know. 😄 

---

Totally unrelated aside: I read that WinXP usage increased 1.20-something percent over the weekend. Long live IE8! :trollface:

**Comment by evs-chris** [comment]
nice!

**Pull request merged**
