### PR TITLE
change tab to 4 spaces

### PR DESCRIPTION
**Pull request by fkmhrk**
## Description:

ractive.d.ts had 2 types of indentation 

- 4 spaces
- tab

I just replaced tab to 4 spaces

## Fixes the following issues:

Just an improvement.

## Is breaking:

No!

### CODE REVIEW

**Comment by ghost** [comment]
Strange how this file was formatted with spaces when the rest of Ractive... is mostly tabs. 😁

**Comment by ghost** [comment]
Oh wait, it's `.ts`, nevermind. Editorconfig wasn't set up for `.ts`. 😁

**Comment by fkmhrk** [comment]
Should I add the following entry to `.editorconfig` ?
(TypeScript guideline says "Use 4 spaces".   https://github.com/Microsoft/TypeScript/wiki/Coding-guidelines)

```
[*.ts]
indent_style = space
indent_size = 4
```

**Comment by ghost** [comment]
Yup, that should be fine. That way, future contributors of `.ts` files (with supported IDEs/editors) automatically benefit from your PR. 😁

**Comment by fkmhrk** [comment]
Added!

**Pull request merged**
