### PR TITLE
First swing at event delegation - RFC

### PR DESCRIPTION
**Pull request by evs-chris**
## Description of the pull request:
Ractive events currently install a listener on their target node, which works out great most of the time, but if you have a large iterative section, attaching event listeners adds a fairly significant overhead. You can manage delegation manually, but it's a little bit painful, because getting in the correct context requires some strange boilerplate.

To address that, this adds support for setting a delegation target and specifying events to be delegated further downstream. To set a target, you add `delegate-click` as an attribute to the element. Then to specify a delegated event, you set `delegate-click="doSomething"` on the source element. When this sees a delegate target, it installs an (or all) appropriate event listener on the target element. When it sees a delegated event, it sets up the fire handler but does nothing further. When the target catches an event, it starts with the target element and walks back up the hierarchy until it reaches the target node while looking for and firing matching delegated event listeners.

Caveats: this only works with events that fire with an original event, so some custom event plugins may not work. It also doesn't really make sense to support component events as delegated, because they don't involve the DOM.

Example:
```html
<table delegate-click>
{{#each lotsOfRows}}
  <tr>
    <td><button delegate-click="@.select(.)">Select</button></td>
    <td>{{.description}}</td>
    <td>{{.something}}</td>
    <td><button delegate-click="event.splice('../../', @index, 1)">Remove</button></td>
  <tr>
{{/each}}
</table>
```

Note that the delegated handlers are written exactly the same as non-delegated handlers would be.

In a benchmark very similar to that example, using delegation reduces render time by ~25% on my machine with 1000 rows, going from 40ms to 30ms on average. Unrender is also a bit quicker on average, as the listeners don't also need to be removed.

### TODO
* [x] Tests

## Fixes the following issues:
The remaining bits of #846

## Is breaking:
Nope

## Reviewers:
Yep

### CODE REVIEW

**Comment by ghost** [comment]
🤔 

Wondering if delegation can simply be an implementation optimization rather than an additional attribute. Like if Ractive detects an `on-*` in a suboptimal spot (like in a repeating section), it attaches the handler to the most optimal ancestor. This way, there's no change in the template syntax/addition of another attribute.

The idea comes from jQuery's `.on()` method. Aside from the change in signature, the handler stays absolutely the same and is unaware of the fact that the attachment was done direct or via delegation. The only noticeable difference is that `event.delegateTarget` now has a value.

For instance, this would attach the click handler on `<table>` instead (escaping both sections). However, `select` would still be run as if it were in the context of the button.

```js
<table>
{{#each lotsOfRows}}
  <tr>
    <td>
    {{#each moarButtons }}<button on-click="@this.select(.)">Select</button>{{/each}}
    </td>
  <tr>
{{/each}}
</table>
```

My 2c.

**Comment by MartinKolarik** [comment]
I agree with @fskreuz that we probably don't need new syntax for this.

**Comment by evs-chris** [comment]
That's how I wanted to approach it to begin with, but I couldn't come up with a method for checking to see if the event should be delegated that wasn't potentially as expensive as just installing the handler. The other side of that is keeping track of the delegate listener when an event directive decides it needs to be delegated. I suppose it could be reference counted or just left in place until the element is removed.

There are also some corner cases with delegation and decorators or anything else that could potentially add event listeners between the delegate and target node. Since the event has already bubbled through to the delegate node, trying to stop the event from one of the delegates is not possible. That case _is_ covered for ractive-managed events, though.

So, we could probably add a flag to elements to see if they are in an iterative section, and if they are use delegated events. Could the cancellation concern be addressed by using a capturing listener for delegates?

**Comment by evs-chris** [comment]
Hmmm. Even using capture would cause some weirdness with listeners being fired out of expected order.

Thinking about it, I would guess that 99% of the time delegation would be fine, and I suppose we could add an instance flag to disable it for those other 1% cases. If that's the accurate, I think I can come up with a way to do automatic delegation. Would that be be fairly universally preferred over manual control as implemented here?

**Comment by MartinKolarik** [comment]
Yes, capture wouldn't really solve it, but I don't think it's a problem. Especially if there's a way to disable delegation, as you suggested. For me, definitely better than manual control.

**Comment by evs-chris** [comment]
Superceded.

**Pull request closed without merging**
