### PR TITLE
Bug #2038

### PR DESCRIPTION
**Pull request by ISNIT0**
We now extend namespaces with a namespaces object that is supplied to the Ractive instance on init.

### CODE REVIEW

**Comment by ISNIT0** [comment]
#2038

**Comment by ISNIT0** [comment]
Odd that check are failing, all tests pass fine on my machine.

**Comment by Madgvox** [comment]
From what I can see, Travis isn't getting to the tests. The linter is throwing up errors. There's a few formatting errors in your changes.

```
src/virtualdom/items/Element/Attribute/helpers/determineNameAndNamespace.js: line 7, col 5, 'utils_object__extend' is not defined.

src/virtualdom/items/Element/prototype/unrender.js: line 82, col 18, Missing semicolon.

src/virtualdom/items/Element/prototype/unrender.js: line 21, col 15, 'global_runloop' is not defined.
```

**Comment by Rich-Harris** [comment]
@ISNIT0 Thanks for submitting this – see my response on #2038. The reason this isn't passing is that you're referring to function names that are generated as part of the build process, e.g. calling `utils_object__extend`. The correct thing to do is to import the function into the module and *then* call it:

```js
import { extend } from '../../utils/object';
const obj = extend(...);
```

Otherwise you're assumed to be referencing a non-existent global, and `extend` gets assigned to a different name to avoid conflicting with said global.

In any case: unfortunately it's not possible to merge this, because the current dev branch differs greatly from the dev branch at the time of the PR. Would like to get to the bottom of this though – if you could supply a fiddle (or even better, a failing test case) it seems like something we can fix.

**Comment by Rich-Harris** [comment]
Closing as fixed via #2305

**Pull request closed without merging**
