### PR TITLE
Remove src from tests

### PR DESCRIPTION
**Pull request by ghost**
## Description of the pull request:

Removes direct `src` dependencies on tests.

## Fixes the following issues:

https://github.com/ractivejs/ractive/issues/2904 . Should also speed up `src` change for `dev:browser` since altering `src` won't cause tests to recompile anymore.

## Is breaking:

No.

## Reviewers:

Everybody!

### CODE REVIEW

**Comment by evs-chris** [comment]
Looking good! 🎉

**Comment by evs-chris** [comment]
Was just looking at creating a sort of meta transition to run multiple transitions in sequence (possibly parallel, but that's trickier), and having `findInViewHierarchy` exposed as maybe `Ractive.findPlugin('transition', 'bounce', instance)` would be super useful.

**Comment by evs-chris** [comment]
@fskreuz I completely forgot about this PR before I did the `getContext` switchover and created a bunch of conflicts 😞. Do you think there's any chance this could land before 0.9?

**Comment by ghost** [comment]
No worries. I'll look into this later today. 😄

**Comment by ghost** [comment]
Still contemplating whether or not I should expose those APIs above. While `normaliseKeypath` is a good candidate to expose since it goes well with the escape and unescape as utility functions, `parseJSON` and `findInViewHierarchy` feel too internal to me.

Still looking for a good way to test them from the public API.

**Comment by evs-chris** [comment]
I've been thinking about dropping the `parseJSON` support for a while. It seems kinda surprising to me actually with the way it's used. If you pass and attribute like this `<div data-foo="{ bar: 42 }">`, which would normally be a string, ractive will try to parse it with `parseJSON` first. I kinda get why it was done originally, but it has some weird implementation details. It can also be replaced with `bind-data-foo={ bar: 42 }` as of 0.9.

I still like `findPlugin` as a front for `findInViewHierarchy` for library purposes - not really meant for general use, but nice for decorator and component authors.

**Comment by evs-chris** [comment]
Pondering for a tiny bit more, I'd say go ahead and expose `parseJSON` for now to land this for 0.9. Since most people probably don't know about the whole bound attribute without an interpolator thing, we can leave it undocumented and pull it out before 1.0. Has the benefit of speeding up attributes slightly and dropping a little more code weight.

**Comment by ghost** [comment]
I think this is good to go.

**Comment by evs-chris** [comment]
The tests! They stand alone! 🎆 🍾

**Pull request merged**
